import type { Locale } from "./config";

type Copy = { title: string; body: string; update: string; later: string; failed: string };
export const iosUpdateCopy: Record<Locale, Copy> = {
  tr: { title: "Logivya'nın yeni sürümü hazır", body: "Yeni özellikler ve düzeltmeler için App Store'dan güncelleyin. Hesabınız ve verileriniz korunur.", update: "Şimdi güncelle", later: "Daha sonra", failed: "App Store açılamadı. Lütfen yeniden deneyin veya App Store'da Logivya'yı arayın." },
  en: { title: "A new Logivya version is available", body: "Update in the App Store for the latest features and fixes. Your account and data are preserved.", update: "Update now", later: "Later", failed: "Could not open the App Store. Try again or search for Logivya in the App Store." },
  ar: { title: "إصدار جديد من Logivya متاح", body: "حدّث من App Store للحصول على أحدث الميزات والإصلاحات. سيُحفظ حسابك وبياناتك.", update: "التحديث الآن", later: "لاحقًا", failed: "تعذر فتح App Store. حاول مجددًا أو ابحث عن Logivya في المتجر." },
  de: { title: "Eine neue Logivya-Version ist verfügbar", body: "Aktualisieren Sie im App Store für neue Funktionen und Korrekturen. Ihr Konto und Ihre Daten bleiben erhalten.", update: "Jetzt aktualisieren", later: "Später", failed: "Der App Store konnte nicht geöffnet werden. Versuchen Sie es erneut oder suchen Sie dort nach Logivya." },
  ro: { title: "O nouă versiune Logivya este disponibilă", body: "Actualizați din App Store pentru funcții noi și remedieri. Contul și datele dvs. se păstrează.", update: "Actualizați acum", later: "Mai târziu", failed: "App Store nu a putut fi deschis. Încercați din nou sau căutați Logivya în magazin." },
  ru: { title: "Доступна новая версия Logivya", body: "Обновите приложение в App Store, чтобы получить новые функции и исправления. Ваш аккаунт и данные сохранятся.", update: "Обновить сейчас", later: "Позже", failed: "Не удалось открыть App Store. Повторите попытку или найдите Logivya в магазине." },
  az: { title: "Logivya-nın yeni versiyası hazırdır", body: "Yeni funksiyalar və düzəlişlər üçün App Store-dan yeniləyin. Hesabınız və məlumatlarınız qorunur.", update: "İndi yenilə", later: "Daha sonra", failed: "App Store açıla bilmədi. Yenidən cəhd edin və ya mağazada Logivya axtarın." },
  tk: { title: "Logivya-nyň täze wersiýasy taýýar", body: "Täze mümkinçilikler we düzedişler üçin App Store arkaly täzeläň. Hasabyňyz we maglumatlaryňyz saklanýar.", update: "Häzir täzele", later: "Soňrak", failed: "App Store açylmady. Täzeden synanyşyň ýa-da dükanda Logivya gözläň." },
  bg: { title: "Налична е нова версия на Logivya", body: "Актуализирайте от App Store за нови функции и поправки. Акаунтът и данните ви се запазват.", update: "Актуализирайте сега", later: "По-късно", failed: "App Store не можа да се отвори. Опитайте отново или потърсете Logivya в магазина." },
  el: { title: "Διατίθεται νέα έκδοση του Logivya", body: "Ενημερώστε από το App Store για νέες λειτουργίες και διορθώσεις. Ο λογαριασμός και τα δεδομένα σας διατηρούνται.", update: "Ενημέρωση τώρα", later: "Αργότερα", failed: "Δεν ήταν δυνατό το άνοιγμα του App Store. Δοκιμάστε ξανά ή αναζητήστε το Logivya στο κατάστημα." },
  uz: { title: "Logivya ilovasining yangi versiyasi mavjud", body: "Yangi imkoniyatlar va tuzatishlar uchun App Store orqali yangilang. Hisobingiz va ma’lumotlaringiz saqlanadi.", update: "Hozir yangilash", later: "Keyinroq", failed: "App Store ochilmadi. Qayta urinib ko‘ring yoki do‘kondan Logivya ilovasini qidiring." },
  sr: { title: "Dostupna je nova verzija aplikacije Logivya", body: "Ažurirajte u App Store-u za nove funkcije i ispravke. Vaš nalog i podaci ostaju sačuvani.", update: "Ažuriraj sada", later: "Kasnije", failed: "App Store nije mogao da se otvori. Pokušajte ponovo ili potražite Logivya u prodavnici." },
};
