const tr = {
  title: "Canlı İlanlar",
  eyebrow: "LOGIVYA PAZAR YERİ",
  matchingEyebrow: "LOGIVYA EŞLEŞTİRME",
  routeAria: "Rota",
  listingFeaturesAria: "İlan özellikleri",
  subtitle: "Güncel yük, araç ve şoför ilanlarını tek akışta takip edin.",
  requests: "Kayıtlı Talepler",
  createRequest: "Talep Oluştur",
  search: "İlanlarda ara",
  all: "Tümü",
  loads: "Yükler",
  vehicles: "Araçlar",
  drivers: "Şoförler",
  global: "Genel Lojistik",
  homeMoving: "Evden Eve",
  partialLoad: "Parça Yük",
  heavyHaul: "Ağır Nakliyat",
  live: "Canlı",
  reconnecting: "Yeniden bağlanıyor",
  loading: "İlanlar yükleniyor…",
  empty: "Bu kapsamda aktif ilan bulunamadı.",
  loadError: "İlanlar şu anda yüklenemedi.",
  retry: "Tekrar dene",
  loadingLabel: "YÜKLEME",
  deliveryLabel: "TESLİM",
  locationLabel: "KONUM",
  detail: "Detayları gör",
  matched: "Bu ilan talebinizle eşleşti",
  backToListings: "Canlı ilanlara dön",
  backToRequests: "Kayıtlı taleplere dön",
  listingUnavailable: "İlan artık aktif değil",
  listingUnavailableText: "Bu ilan süresi dolduğu veya yayından kaldırıldığı için iletişim işlemleri kapatıldı.",
  advertiser: "İlan veren",
  source: "İlan Kaynağı",
  published: "Yayınlanma",
  vehicle: "Araç tipi",
  tonnage: "Tonaj",
  vehicleCount: "Araç sayısı",
  loadingDate: "Yükleme / uygunluk tarihi",
  availableUntil: "Uygunluk bitişi",
  cargo: "Yük türü",
  price: "Fiyat",
  customs: "Gümrük bilgisi",
  container: "Konteyner durumu",
  international: "Uluslararası taşıma",
  adr: "ADR uygunluğu",
  preferredRoute: "Tercih edilen rota",
  listingType: "İlan türü",
  licenses: "Ehliyet sınıfları",
  experience: "Deneyim",
  employment: "Çalışma biçimi",
  certificates: "Belgeler",
  yes: "Evet",
  no: "Hayır",
  years: "yıl",
  call: "Ara",
  whatsapp: "WhatsApp",
  contactMissing: "Geçerli bir herkese açık iletişim numarası belirtilmedi.",
  report: "İlanı bildir",
  detailLoading: "İlan detayı yükleniyor…",
  detailNotFound: "İlan bulunamadı veya görüntüleme yetkiniz yok.",
  requestsTitle: "Kayıtlı Talepler",
  requestsSubtitle: "Aradığınız yük, araç veya şoför kriterlerini kaydedin; yeni eşleşmeleri burada görün.",
  notificationsTitle: "Talep eşleşmeleri",
  noNotifications: "Henüz yeni bir eşleşme bildirimi yok.",
  openMatch: "Eşleşen ilanı aç",
  noRequests: "Henüz kayıtlı talebiniz yok.",
  active: "Aktif",
  paused: "Duraklatıldı",
  fulfilled: "Tamamlandı",
  expired: "Süresi doldu",
  matches: "eşleşme",
  expires: "Bitiş",
  requestKind: "Talep türü",
  requestTitle: "Talep başlığı",
  requestTitlePlaceholder: "Örn. Mersin–İstanbul tenteli araç",
  origin: "Yükleme / çıkış",
  destination: "Teslim / varış",
  location: "Konum",
  availableFrom: "Başlangıç tarihi",
  availableUntilForm: "Bitiş tarihi",
  trailer: "Araç tipi",
  anyTrailer: "Farketmez",
  minWeight: "En az ton",
  maxWeight: "En fazla ton",
  sector: "Lojistik alanı",
  notifications: "Yeni eşleşmeler için bildirim gönder",
  duration: "Talep süresi",
  days30: "30 gün",
  days60: "60 gün",
  days90: "90 gün",
  save: "Talebi kaydet",
  saving: "Kaydediliyor…",
  saved: "Talebiniz kaydedildi ve eşleştirme başlatıldı.",
  formError: "Talep kaydedilemedi. Alanları kontrol edip yeniden deneyin.",
  loadKind: "Yük arıyorum",
  vehicleKind: "Araç arıyorum",
  driverKind: "Şoför arıyorum",
} as const;

const en: Record<keyof typeof tr, string> = {
  title: "Live Listings", eyebrow: "LOGIVYA MARKETPLACE", matchingEyebrow: "LOGIVYA MATCHING", routeAria: "Route", listingFeaturesAria: "Listing features", subtitle: "Follow current load, vehicle, and driver listings in one feed.", requests: "Saved Demands", createRequest: "Create Demand", search: "Search listings", all: "All", loads: "Loads", vehicles: "Vehicles", drivers: "Drivers", global: "General Logistics", homeMoving: "Home Moving", partialLoad: "Partial Load", heavyHaul: "Heavy Haul", live: "Live", reconnecting: "Reconnecting", loading: "Loading listings…", empty: "No active listings were found in this scope.", loadError: "Listings could not be loaded right now.", retry: "Try again", loadingLabel: "LOADING", deliveryLabel: "DELIVERY", locationLabel: "LOCATION", detail: "View details", matched: "This listing matched your demand", backToListings: "Back to live listings", backToRequests: "Back to saved demands", listingUnavailable: "This listing is no longer active", listingUnavailableText: "Contact actions are disabled because the listing expired or was removed.", advertiser: "Advertiser", source: "Listing source", published: "Published", vehicle: "Vehicle type", tonnage: "Tonnage", vehicleCount: "Vehicle count", loadingDate: "Loading / availability date", availableUntil: "Available until", cargo: "Cargo", price: "Price", customs: "Customs information", container: "Container status", international: "International transport", adr: "ADR suitability", preferredRoute: "Preferred route", listingType: "Listing type", licenses: "Licence classes", experience: "Experience", employment: "Employment", certificates: "Certificates", yes: "Yes", no: "No", years: "years", call: "Call", whatsapp: "WhatsApp", contactMissing: "No valid public contact number was provided.", report: "Report listing", detailLoading: "Loading listing details…", detailNotFound: "The listing was not found or you do not have access.", requestsTitle: "Saved Demands", requestsSubtitle: "Save load, vehicle, or driver criteria and review new matches here.", notificationsTitle: "Demand matches", noNotifications: "There are no new match notifications yet.", openMatch: "Open matching listing", noRequests: "You do not have a saved demand yet.", active: "Active", paused: "Paused", fulfilled: "Fulfilled", expired: "Expired", matches: "matches", expires: "Expires", requestKind: "Demand type", requestTitle: "Demand title", requestTitlePlaceholder: "Example: Mersin–Istanbul curtain-side vehicle", origin: "Loading / origin", destination: "Delivery / destination", location: "Location", availableFrom: "Start date", availableUntilForm: "End date", trailer: "Vehicle type", anyTrailer: "Any", minWeight: "Minimum tonnes", maxWeight: "Maximum tonnes", sector: "Logistics area", notifications: "Notify me about new matches", duration: "Demand duration", days30: "30 days", days60: "60 days", days90: "90 days", save: "Save demand", saving: "Saving…", saved: "Your demand was saved and matching has started.", formError: "The demand could not be saved. Check the fields and try again.", loadKind: "Looking for a load", vehicleKind: "Looking for a vehicle", driverKind: "Looking for a driver",
};

export type MarketplaceCopy = typeof tr;

export function marketplaceCopy(locale: string): MarketplaceCopy {
  return (locale === "tr" ? tr : en) as MarketplaceCopy;
}
