import { uzbekMarketplaceCopy } from "./copy-uz";
import additionalCopy from "../../../shared/marketplace-copy-locales.json";

const tr = {
  title: "Canlı İlanlar",
  eyebrow: "LOGIVYA PAZAR YERİ",
  matchingEyebrow: "LOGIVYA EŞLEŞTİRME",
  routeAria: "Rota",
  listingFeaturesAria: "İlan özellikleri",
  subtitle: "Güncel yük, araç ve şoför ilanlarını tek akışta takip edin.",
  requests: "Kayıtlı Talepler",
  createRequest: "Talep Oluştur",
  search: "İlanlarda ara",
  all: "Tümü",
  loads: "Yükler",
  vehicles: "Araçlar",
  drivers: "Şoförler",
  global: "Genel Lojistik",
  homeMoving: "Evden Eve",
  partialLoad: "Parça Yük",
  heavyHaul: "Ağır Nakliyat",
  live: "Canlı",
  reconnecting: "Yeniden bağlanıyor",
  loading: "İlanlar yükleniyor…",
  empty: "Bu kapsamda aktif ilan bulunamadı.",
  loadError: "İlanlar şu anda yüklenemedi.",
  retry: "Tekrar dene",
  loadingLabel: "YÜKLEME",
  deliveryLabel: "TESLİM",
  locationLabel: "KONUM",
  detail: "Detayları gör",
  matched: "Bu ilan talebinizle eşleşti",
  backToListings: "Canlı ilanlara dön",
  backToRequests: "Kayıtlı taleplere dön",
  listingUnavailable: "İlan artık aktif değil",
  listingUnavailableText: "Bu ilan süresi dolduğu veya yayından kaldırıldığı için iletişim işlemleri kapatıldı.",
  advertiser: "İlan veren",
  source: "İlan Kaynağı",
  published: "Yayınlanma",
  vehicle: "Araç tipi",
  tonnage: "Tonaj",
  vehicleCount: "Araç sayısı",
  loadingDate: "Yükleme / uygunluk tarihi",
  availableUntil: "Uygunluk bitişi",
  cargo: "Yük türü",
  price: "Fiyat",
  customs: "Gümrük bilgisi",
  container: "Konteyner durumu",
  international: "Uluslararası taşıma",
  adr: "ADR uygunluğu",
  preferredRoute: "Tercih edilen rota",
  listingType: "İlan türü",
  licenses: "Ehliyet sınıfları",
  experience: "Deneyim",
  employment: "Çalışma biçimi",
  certificates: "Belgeler",
  yes: "Evet",
  no: "Hayır",
  years: "yıl",
  call: "Ara",
  whatsapp: "WhatsApp",
  contactMissing: "Geçerli bir herkese açık iletişim numarası belirtilmedi.",
  report: "İlanı bildir",
  detailLoading: "İlan detayı yükleniyor…",
  detailNotFound: "İlan bulunamadı veya görüntüleme yetkiniz yok.",
  requestsTitle: "Kayıtlı Talepler",
  requestsSubtitle: "Aradığınız yük, araç veya şoför kriterlerini kaydedin; yeni eşleşmeleri burada görün.",
  notificationsTitle: "Talep eşleşmeleri",
  noNotifications: "Henüz yeni bir eşleşme bildirimi yok.",
  openMatch: "Eşleşen ilanı aç",
  noRequests: "Henüz kayıtlı talebiniz yok.",
  active: "Aktif",
  paused: "Duraklatıldı",
  fulfilled: "Tamamlandı",
  expired: "Süresi doldu",
  matches: "eşleşme",
  expires: "Bitiş",
  requestKind: "Talep türü",
  requestTitle: "Talep başlığı",
  requestTitlePlaceholder: "Örn. Mersin–İstanbul tenteli araç",
  origin: "Yükleme / çıkış",
  destination: "Teslim / varış",
  location: "Konum",
  availableFrom: "Başlangıç tarihi",
  availableUntilForm: "Bitiş tarihi",
  trailer: "Araç tipi",
  anyTrailer: "Farketmez",
  minWeight: "En az ton",
  maxWeight: "En fazla ton",
  sector: "Lojistik alanı",
  notifications: "Yeni eşleşmeler için bildirim gönder",
  duration: "Talep süresi",
  days30: "30 gün",
  days60: "60 gün",
  days90: "90 gün",
  save: "Talebi kaydet",
  saving: "Kaydediliyor…",
  saved: "Talebiniz kaydedildi ve eşleştirme başlatıldı.",
  formError: "Talep kaydedilemedi. Alanları kontrol edip yeniden deneyin.",
  loadKind: "Yük arıyorum",
  vehicleKind: "Araç arıyorum",
  driverKind: "Şoför arıyorum",
} as const;

const en: Record<keyof typeof tr, string> = {
  title: "Live Listings", eyebrow: "LOGIVYA MARKETPLACE", matchingEyebrow: "LOGIVYA MATCHING", routeAria: "Route", listingFeaturesAria: "Listing features", subtitle: "Follow current load, vehicle, and driver listings in one feed.", requests: "Saved Demands", createRequest: "Create Demand", search: "Search listings", all: "All", loads: "Loads", vehicles: "Vehicles", drivers: "Drivers", global: "General Logistics", homeMoving: "Home Moving", partialLoad: "Partial Load", heavyHaul: "Heavy Haul", live: "Live", reconnecting: "Reconnecting", loading: "Loading listings…", empty: "No active listings were found in this scope.", loadError: "Listings could not be loaded right now.", retry: "Try again", loadingLabel: "LOADING", deliveryLabel: "DELIVERY", locationLabel: "LOCATION", detail: "View details", matched: "This listing matched your demand", backToListings: "Back to live listings", backToRequests: "Back to saved demands", listingUnavailable: "This listing is no longer active", listingUnavailableText: "Contact actions are disabled because the listing expired or was removed.", advertiser: "Advertiser", source: "Listing source", published: "Published", vehicle: "Vehicle type", tonnage: "Tonnage", vehicleCount: "Vehicle count", loadingDate: "Loading / availability date", availableUntil: "Available until", cargo: "Cargo", price: "Price", customs: "Customs information", container: "Container status", international: "International transport", adr: "ADR suitability", preferredRoute: "Preferred route", listingType: "Listing type", licenses: "Licence classes", experience: "Experience", employment: "Employment", certificates: "Certificates", yes: "Yes", no: "No", years: "years", call: "Call", whatsapp: "WhatsApp", contactMissing: "No valid public contact number was provided.", report: "Report listing", detailLoading: "Loading listing details…", detailNotFound: "The listing was not found or you do not have access.", requestsTitle: "Saved Demands", requestsSubtitle: "Save load, vehicle, or driver criteria and review new matches here.", notificationsTitle: "Demand matches", noNotifications: "There are no new match notifications yet.", openMatch: "Open matching listing", noRequests: "You do not have a saved demand yet.", active: "Active", paused: "Paused", fulfilled: "Fulfilled", expired: "Expired", matches: "matches", expires: "Expires", requestKind: "Demand type", requestTitle: "Demand title", requestTitlePlaceholder: "Example: Mersin–Istanbul curtain-side vehicle", origin: "Loading / origin", destination: "Delivery / destination", location: "Location", availableFrom: "Start date", availableUntilForm: "End date", trailer: "Vehicle type", anyTrailer: "Any", minWeight: "Minimum tonnes", maxWeight: "Maximum tonnes", sector: "Logistics area", notifications: "Notify me about new matches", duration: "Demand duration", days30: "30 days", days60: "60 days", days90: "90 days", save: "Save demand", saving: "Saving…", saved: "Your demand was saved and matching has started.", formError: "The demand could not be saved. Check the fields and try again.", loadKind: "Looking for a load", vehicleKind: "Looking for a vehicle", driverKind: "Looking for a driver",
};

const ar: Record<keyof typeof tr, string> = {
  title: "الإعلانات المباشرة", eyebrow: "سوق LOGIVYA", matchingEyebrow: "مطابقة LOGIVYA", routeAria: "المسار", listingFeaturesAria: "ميزات الإعلان", subtitle: "تابع إعلانات الشحنات والمركبات والسائقين الحالية في تدفق واحد.", requests: "الطلبات المحفوظة", createRequest: "إنشاء طلب", search: "البحث في الإعلانات", all: "الكل", loads: "الشحنات", vehicles: "المركبات", drivers: "السائقون", global: "الخدمات اللوجستية العامة", homeMoving: "النقل المنزلي", partialLoad: "الشحن الجزئي", heavyHaul: "النقل الثقيل", live: "مباشر", reconnecting: "إعادة الاتصال", loading: "جارٍ تحميل الإعلانات…", empty: "لم يتم العثور على إعلانات نشطة ضمن هذا النطاق.", loadError: "تعذر تحميل الإعلانات حاليًا.", retry: "إعادة المحاولة", loadingLabel: "التحميل", deliveryLabel: "التسليم", locationLabel: "الموقع", detail: "عرض التفاصيل", matched: "يطابق هذا الإعلان طلبك", backToListings: "العودة إلى الإعلانات المباشرة", backToRequests: "العودة إلى الطلبات المحفوظة", listingUnavailable: "لم يعد هذا الإعلان نشطًا", listingUnavailableText: "تم تعطيل وسائل الاتصال لأن الإعلان انتهى أو أزيل.", advertiser: "صاحب الإعلان", source: "مصدر الإعلان", published: "تاريخ النشر", vehicle: "نوع المركبة", tonnage: "الحمولة", vehicleCount: "عدد المركبات", loadingDate: "تاريخ التحميل أو التوفر", availableUntil: "متاح حتى", cargo: "نوع الحمولة", price: "السعر", customs: "معلومات الجمارك", container: "حالة الحاوية", international: "نقل دولي", adr: "ملاءمة ADR", preferredRoute: "المسار المفضل", listingType: "نوع الإعلان", licenses: "فئات الرخص", experience: "الخبرة", employment: "نمط العمل", certificates: "الشهادات", yes: "نعم", no: "لا", years: "سنوات", call: "اتصال", whatsapp: "WhatsApp", contactMissing: "لم يتم تقديم رقم اتصال عام صالح.", report: "الإبلاغ عن الإعلان", detailLoading: "جارٍ تحميل تفاصيل الإعلان…", detailNotFound: "لم يتم العثور على الإعلان أو لا تملك صلاحية عرضه.", requestsTitle: "الطلبات المحفوظة", requestsSubtitle: "احفظ معايير الشحنة أو المركبة أو السائق وراجع التطابقات الجديدة هنا.", notificationsTitle: "تطابقات الطلب", noNotifications: "لا توجد إشعارات تطابق جديدة حتى الآن.", openMatch: "فتح الإعلان المطابق", noRequests: "ليس لديك طلب محفوظ حتى الآن.", active: "نشط", paused: "متوقف مؤقتًا", fulfilled: "مكتمل", expired: "منتهي", matches: "تطابقات", expires: "ينتهي", requestKind: "نوع الطلب", requestTitle: "عنوان الطلب", requestTitlePlaceholder: "مثال: مركبة ستائرية من مرسين إلى إسطنبول", origin: "التحميل أو الانطلاق", destination: "التسليم أو الوجهة", location: "الموقع", availableFrom: "تاريخ البدء", availableUntilForm: "تاريخ الانتهاء", trailer: "نوع المركبة", anyTrailer: "أي نوع", minWeight: "الحد الأدنى بالأطنان", maxWeight: "الحد الأقصى بالأطنان", sector: "المجال اللوجستي", notifications: "إشعاري بالتطابقات الجديدة", duration: "مدة الطلب", days30: "30 يومًا", days60: "60 يومًا", days90: "90 يومًا", save: "حفظ الطلب", saving: "جارٍ الحفظ…", saved: "تم حفظ طلبك وبدأت المطابقة.", formError: "تعذر حفظ الطلب. تحقق من الحقول وحاول مرة أخرى.", loadKind: "أبحث عن شحنة", vehicleKind: "أبحث عن مركبة", driverKind: "أبحث عن سائق",
};

export type MarketplaceCopy = typeof tr;

export function marketplaceCopy(locale: string): MarketplaceCopy {
  const uz: Record<keyof typeof tr, string> = uzbekMarketplaceCopy;
  return (locale === "tr" ? tr : locale === "ar" ? ar : locale === "uz" ? uz : (additionalCopy as Record<string, Record<string, string>>)[locale] ?? en) as MarketplaceCopy;
}
