export const uzbekMarketplaceCopy = {
  title: "Jonli e’lonlar",
  eyebrow: "LOGIVYA LOGISTIKA BOZORI",
  matchingEyebrow: "LOGIVYA MOSLASHTIRISH",
  routeAria: "Yo‘nalish",
  listingFeaturesAria: "E’lon xususiyatlari",
  subtitle: "Yuk, transport va haydovchi e’lonlarini bir joyda kuzating.",
  requests: "Saqlangan so‘rovlar",
  createRequest: "So‘rov yaratish",
  search: "E’lonlarni qidirish",
  all: "Barchasi",
  loads: "Yuklar",
  vehicles: "Transportlar",
  drivers: "Haydovchilar",
  global: "Umumiy logistika",
  homeMoving: "Uy ko‘chirish",
  partialLoad: "Qisman yuk",
  heavyHaul: "Og‘ir yuk tashish",
  live: "Jonli",
  reconnecting: "Qayta ulanmoqda",
  loading: "E’lonlar yuklanmoqda…",
  empty: "Bu bo‘limda faol e’lon topilmadi.",
  loadError: "Hozir e’lonlarni yuklab bo‘lmadi.",
  retry: "Qayta urinish",
  loadingLabel: "YUKLASH",
  deliveryLabel: "YETKAZISH",
  locationLabel: "JOYLASHUV",
  detail: "Batafsil ko‘rish",
  matched: "Bu e’lon so‘rovingizga mos keldi",
  backToListings: "Jonli e’lonlarga qaytish",
  backToRequests: "Saqlangan so‘rovlarga qaytish",
  listingUnavailable: "E’lon endi faol emas",
  listingUnavailableText: "E’lon muddati tugagani yoki o‘chirilgani sababli bog‘lanish imkoni yopildi.",
  advertiser: "E’lon beruvchi",
  source: "E’lon manbasi",
  published: "E’lon qilingan sana",
  vehicle: "Transport turi",
  tonnage: "Og‘irlik (tonna)",
  vehicleCount: "Transport soni",
  loadingDate: "Yuklash / mavjudlik sanasi",
  availableUntil: "Mavjudlik tugashi",
  cargo: "Yuk turi",
  price: "Narx",
  customs: "Bojxona ma’lumoti",
  container: "Konteyner holati",
  international: "Xalqaro tashish",
  adr: "ADR muvofiqligi",
  preferredRoute: "Afzal yo‘nalish",
  listingType: "E’lon turi",
  licenses: "Haydovchilik guvohnomasi toifalari",
  experience: "Tajriba",
  employment: "Ishlash shakli",
  certificates: "Hujjatlar",
  yes: "Ha",
  no: "Yo‘q",
  years: "yil",
  call: "Qo‘ng‘iroq qilish",
  whatsapp: "WhatsApp",
  contactMissing: "Yaroqli ochiq aloqa raqami ko‘rsatilmagan.",
  report: "E’lon haqida shikoyat qilish",
  detailLoading: "E’lon tafsilotlari yuklanmoqda…",
  detailNotFound: "E’lon topilmadi yoki uni ko‘rish huquqingiz yo‘q.",
  requestsTitle: "Saqlangan so‘rovlar",
  requestsSubtitle: "Yuk, transport yoki haydovchi mezonlarini saqlang va yangi mosliklarni shu yerda ko‘ring.",
  notificationsTitle: "So‘rovga mos e’lonlar",
  noNotifications: "Hozircha yangi moslik bildirishnomasi yo‘q.",
  openMatch: "Mos e’lonni ochish",
  noRequests: "Hozircha saqlangan so‘rovingiz yo‘q.",
  active: "Faol",
  paused: "To‘xtatilgan",
  fulfilled: "Bajarilgan",
  expired: "Muddati tugagan",
  matches: "moslik",
  expires: "Tugash sanasi",
  requestKind: "So‘rov turi",
  requestTitle: "So‘rov sarlavhasi",
  requestTitlePlaceholder: "Masalan: Mersin–Istanbul tentli transport",
  origin: "Yuklash / jo‘nash",
  destination: "Yetkazish / borish",
  location: "Joylashuv",
  availableFrom: "Boshlanish sanasi",
  availableUntilForm: "Tugash sanasi",
  trailer: "Transport turi",
  anyTrailer: "Farqi yo‘q",
  minWeight: "Eng kam tonna",
  maxWeight: "Eng ko‘p tonna",
  sector: "Logistika sohasi",
  notifications: "Yangi mosliklar haqida xabar berish",
  duration: "So‘rov muddati",
  days30: "30 kun",
  days60: "60 kun",
  days90: "90 kun",
  save: "So‘rovni saqlash",
  saving: "Saqlanmoqda…",
  saved: "So‘rovingiz saqlandi va moslashtirish boshlandi.",
  formError: "So‘rovni saqlab bo‘lmadi. Maydonlarni tekshirib, qayta urinib ko‘ring.",
  loadKind: "Yuk qidiryapman",
  vehicleKind: "Transport qidiryapman",
  driverKind: "Haydovchi qidiryapman",
};
