import Link from "next/link";
import { Database, Files, ShieldCheck, ArrowUpRight } from "lucide-react";
import { getRecoveryEvidence, recoveryState } from "@/server/monitoring/recovery-evidence";
import { AdminRecoveryRefresh } from "./admin-recovery-refresh";

export async function AdminRecoveryOverview({ tr, recovery = false }: { tr: boolean; recovery?: boolean }) {
  const evidence = await getRecoveryEvidence();
  const report = evidence.report;
  const text = (turkish: string, english: string) => tr ? turkish : english;
  const date = (value?: string) => value ? new Intl.DateTimeFormat(tr ? "tr-TR" : "en-GB", { dateStyle: "medium", timeStyle: "short", timeZone: "Europe/Istanbul" }).format(new Date(value)) : text("Henüz doğrulanmadı", "Not yet verified");
  const states = { VERIFIED: text("Doğrulandı", "Verified"), STALE: text("Güncel yedek gerekli", "Fresh evidence required"), FAILED: text("İşlem kontrol edilmeli", "Attention required"), UNKNOWN: text("Kanıt bulunamadı", "Evidence unavailable") };
  const cards = [
    { kind: "database" as const, icon: Database, title: text("Veritabanı yedeği", "Database backup"), detail: text("Saatlik • şifreli • iki depodan geri okuma", "Hourly · encrypted · readback from two stores") },
    { kind: "files" as const, icon: Files, title: text("Dosyalar ve yapılandırma", "Files and configuration"), detail: text("Günlük • medya, sunucu ayarları ve kaynak kodu", "Daily · media, server configuration and source") },
    { kind: "drill" as const, icon: ShieldCheck, title: text("Kurtarma tatbikatı", "Recovery exercise"), detail: text("Günlük • uzak kopyalardan izole geri yükleme", "Daily · isolated restore from remote copies") },
  ];
  return <div className="space-y-6">
    <header className="flex flex-wrap items-start justify-between gap-4">
      <div><p className="text-xs font-semibold uppercase tracking-widest text-orange-600">{text("İş sürekliliği", "Business continuity")}</p><h1 className="mt-2 text-2xl font-semibold sm:text-3xl">{recovery ? text("Felaket kurtarma", "Disaster recovery") : text("Yedekleme merkezi", "Backup center")}</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted">{text("Gerçek yedekleme ve geri yükleme işlerinden alınan imzalı sonuçlar. Saatler Türkiye saatidir.", "Signed results from actual backup and restore jobs. Times are shown in Istanbul time.")}</p></div>
      <AdminRecoveryRefresh tr={tr} />
    </header>
    <nav aria-label={text("Kurtarma bölümleri", "Recovery sections")} className="flex flex-wrap gap-2">
      {[ ["/admin/system/backups", text("Yedekler", "Backups")], ["/admin/disaster-recovery", text("Felaket kurtarma", "Disaster recovery")], ["/admin/system/health", text("Sistem sağlığı", "System health")] ].map(([href, label]) => <Link key={href} href={href} className="inline-flex min-h-11 items-center gap-2 rounded-xl border px-4 py-2 text-sm hover:bg-orange-50">{label}<ArrowUpRight className="size-4" aria-hidden /></Link>)}
    </nav>
    {!evidence.available ? <div role="status" className="rounded-2xl border border-amber-300 bg-amber-50 p-5 text-sm text-amber-900">{text("Güncel ve geçerli imzalı rapor okunamadı. Sonuçlar doğrulanana kadar sistem hazır gösterilmez.", "A current, valid signed report could not be read. Readiness remains unverified.")} <span className="block mt-2 font-mono text-xs">{evidence.errorCode}</span></div> : null}
    <div className="grid gap-4 lg:grid-cols-3">{cards.map(({ kind, icon: Icon, title, detail }) => {
      const state = recoveryState(evidence, kind);
      return <a key={kind} href={`#${kind}`} className="panel block rounded-2xl p-5 transition-shadow hover:shadow-md focus-visible:outline-2 focus-visible:outline-orange-500"><div className="flex items-center justify-between"><Icon className="size-6 text-orange-500" aria-hidden /><ArrowUpRight className="size-4 text-muted" aria-hidden /></div><h2 className="mt-4 font-semibold">{title}</h2><p className={`mt-2 text-lg font-semibold ${state === "VERIFIED" ? "text-emerald-600" : "text-amber-700"}`}>{states[state]}</p><p className="mt-2 text-sm">{date(report?.[kind]?.completedAt)}</p><p className="mt-2 text-xs leading-5 text-muted">{detail}</p></a>;
    })}</div>
    <section id="database" className="panel scroll-mt-24 rounded-2xl p-5"><h2 className="text-lg font-semibold">{text("Veritabanı koruması", "Database protection")}</h2><dl className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Detail label={text("Yedek sıklığı", "Backup interval")} value={text("Her saat", "Every hour")} /><Detail label={text("Veri kaybı hedefi (RPO)", "Data loss objective (RPO)")} value={text("En fazla 90 dakika", "At most 90 minutes")} /><Detail label={text("Şifreleme ve bütünlük", "Encryption and integrity")} value="AES-256-GCM + SHA-256 + HMAC" /><Detail label={text("Uzak kopyalar", "Remote copies")} value={report?.database ? text("2 / 2 geri okuma doğrulandı", "2 / 2 readbacks verified") : "—"} /></dl>{report?.database ? <p className="mt-4 break-all text-xs text-muted">{report.database.backupId} · {(report.database.sizeBytes / 1024 / 1024).toFixed(1)} MB</p> : null}<p className="mt-4 text-sm text-muted">{text("Bu düzen saatlik mantıksal yedek alır. Saniye veya dakika seçerek geri dönüş (PITR) henüz etkin değildir.", "This schedule creates hourly logical backups. Point-in-time recovery (PITR) is not enabled.")}</p></section>
    <section className="panel rounded-2xl p-5"><h2 className="text-lg font-semibold">{text("Saklama düzeni", "Retention policy")}</h2><p className="mt-3 text-sm leading-7 text-muted">{text("Yeni yedekler uzak depolarda en az 30 gün, sunucuda 48 saat saklanır. Temizlik yalnız güncel yedekler ve başarılı kurtarma tatbikatı varsa çalışır. Önceki düzene ait eski yedekler bu işlemin kapsamı dışındadır.", "New backups are retained remotely for at least 30 days and locally for 48 hours. Cleanup requires fresh backups and a successful restore exercise. Legacy backups remain outside this policy.")}</p><p className="mt-2 text-sm">{text("Son saklama kontrolü: ", "Last retention check: ")}{report?.retentionJob?.status === "SUCCEEDED" ? date(report.retentionJob.completedAt) : text("Doğrulama bekleniyor", "Awaiting verification")}</p></section>
    <section className="panel rounded-2xl p-5"><h2 className="text-lg font-semibold">{text("Silme ve üzerine yazma koruması", "Deletion and overwrite protection")}</h2><p className={`mt-3 font-semibold ${report?.policy.immutableStorageVerified ? "text-emerald-600" : "text-amber-700"}`}>{report?.policy.immutableStorageVerified ? text("Son ayar kontrolünde iki depoda etkin · 30 gün", "Enabled in both stores at last settings review · 30 days") : text("Güncel ayar kontrolü gerekli", "Current settings review required")}</p><dl className="mt-4 grid gap-4 sm:grid-cols-2"><Detail label={text("Cloudflare ayar kontrolü", "Cloudflare settings review")} value={date(report?.retentionLock?.checkedAt)} /><Detail label={text("Sonraki kontrol tarihi", "Next review due")} value={date(report?.retentionLock?.reviewDueAt)} /></dl><p className="mt-3 text-sm leading-6 text-muted">{text("Koruma yeni yedek düzenindeki veritabanı ve dosya kopyalarını kapsar. Bu tarih Cloudflare panelindeki ayar doğrulamasıdır; sürekli sağlayıcı izlemesi değildir. Yetkili hesap yöneticisi kilit kuralını değiştirebildiği için bağımsız kopya gereksinimi sürer.", "Protection covers database and file copies in the new backup layout. This is a dated Cloudflare dashboard review, not continuous provider monitoring. Authorized account administrators can change the rule, so an independent copy is still required.")}</p></section>
    <section id="files" className="panel scroll-mt-24 rounded-2xl p-5"><h2 className="text-lg font-semibold">{text("Dosya ve sunucu kapsamı", "Files and server coverage")}</h2><p className="mt-3 text-sm leading-7 text-muted">{text("Yüklenen medya, sunucu Compose yapılandırması, kullanılan çalışma zamanı sırları, yayın kaynak kodu ve konteyner sürüm envanteri şifreli arşive alınır. Yedek çözme anahtarı bu arşive konulmaz.", "Uploaded media, Compose configuration, active runtime secrets, release source and container inventory are encrypted together. The backup decryption key is excluded.")}</p><p className="mt-3 text-sm">{text("Son başarılı yedek: ", "Last successful backup: ")}{date(report?.files?.completedAt)}</p></section>
    <section id="drill" className="panel scroll-mt-24 rounded-2xl p-5"><h2 className="text-lg font-semibold">{text("Gerçek geri yükleme testi", "Actual restore test")}</h2><p className="mt-3 text-sm leading-7 text-muted">{text("İki uzak veritabanı kopyası ayrı ayrı indirilip dış bağlantısı kapalı PostgreSQL ortamında açılır. Sekiz kritik tablonun kayıt sayısı ve şema geçişleri karşılaştırılır. Dosya arşivi ağsız ortamda açılır; geçici kaynaklar temizlenir.", "Both remote database copies are separately restored into isolated PostgreSQL. Eight critical table counts and migrations are compared. The file archive is extracted without network access and temporary resources are removed.")}</p><dl className="mt-4 grid gap-4 sm:grid-cols-3"><Detail label={text("Son başarılı tatbikat", "Last successful exercise")} value={date(report?.drill?.completedAt)} /><Detail label={text("Ölçülen test süresi", "Measured exercise duration")} value={report?.drill ? `${report.drill.durationSeconds} ${text("saniye", "seconds")}` : "—"} /><Detail label={text("Tam hizmet geri dönüş hedefi", "Full service recovery objective")} value={text("4 saat • henüz doğrulanmadı", "4 hours · not yet verified")} /></dl></section>
    <section className="rounded-2xl border border-amber-300 bg-amber-50 p-5 text-amber-950"><h2 className="font-semibold">{text("Tam felaket hazırlığı için kalanlar", "Remaining recovery gaps")}</h2><ul className="mt-3 list-disc space-y-2 pl-5 text-sm leading-6"><li>{text("İki depo aynı Cloudflare hesabını kullanıyor. Bağımsız sağlayıcı ve ayrı erişim anahtarlarıyla üçüncü kopya gerekli.", "Both stores share one Cloudflare account. A third copy with an independent provider and separate credentials is required.")}</li>{!report?.policy.immutableStorageVerified ? <li>{text("Saklama kilidi için güncel sağlayıcı ayar kontrolü gerekli.", "Locked retention requires a current provider settings review.")}</li> : null}<li>{text("Sunucu dışındaki çözme anahtarının kurtarılabilirliği henüz doğrulanmadı.", "Recovery of the decryption key outside this server remains unverified.")}</li><li>{text("Yeni bir sunucuda tüm hizmetlerin geri dönüşü ayrıca sınanmalı. Veritabanı test süresi, tüm platformun geri dönüş süresi değildir.", "A complete service restore on a new server still needs testing. Database exercise time is not full platform recovery time.")}</li></ul></section>
    <p className="text-xs text-muted">{text("İmzalı rapor: ", "Signed report: ")}{date(report?.generatedAt)} · {text("Rapor her 5 dakikada yenilenir. Eski raporlar başarılı sayılmaz.", "Reports refresh every 5 minutes. Stale evidence is not treated as success.")}</p>
  </div>;
}

function Detail({ label, value }: { label: string; value: string }) {
  return <div><dt className="text-xs text-muted">{label}</dt><dd className="mt-1 break-words text-sm font-semibold">{value}</dd></div>;
}
