"use client";
/* eslint-disable react-hooks/set-state-in-effect */
import { FormEvent, useCallback, useEffect, useState } from "react";
import { LoaderCircle, Search } from "lucide-react";
type Subscription={id:string;status:string;currentPeriodEndsAt?:string;plan:{name:string}};
type Company={id:string;name:string;email?:string;owner:{email:string};billingProfile?:{legalName?:string};subscriptions:Subscription[]};
const field="rounded-xl border bg-white px-3 py-3 text-sm",panel="rounded-2xl border bg-card p-6",button="rounded-xl border bg-card px-3 py-2 text-xs font-semibold hover:bg-primary-soft";
export function AdminSubscriptionsPage(){
  const[companies,setCompanies]=useState<Company[]|null>(null),[status,setStatus]=useState(""),[query,setQuery]=useState("");
  const load=useCallback(async(search="")=>{const r=await fetch(`/api/admin/companies${search?`?q=${encodeURIComponent(search)}`:""}`);const value=await r.json();if(!r.ok)throw new Error(value.error);setCompanies(value.companies)},[]);
  useEffect(()=>{void load().catch(e=>setStatus(e.message))},[load]);
  async function activate(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const r=await fetch("/api/admin/subscriptions/manual-activate",{method:"POST",headers:{"content-type":"application/json","idempotency-key":crypto.randomUUID()},body:JSON.stringify(Object.fromEntries(form))});const value=await r.json();setStatus(r.ok?"Abonelik, ödeme ve taslak fatura oluşturuldu.":value.error);void load(query)}
  async function mutate(subscriptionId:string,action:"cancel"|"reactivate"|"extend"){const body=action==="extend"?{endsAt:window.prompt("Yeni bitiş tarihi (YYYY-MM-DD)")}:{};if(action==="extend"&&!body.endsAt)return;const r=await fetch(`/api/admin/subscriptions/${subscriptionId}/${action}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const value=await r.json();setStatus(r.ok?"İşlem tamamlandı.":value.error);void load(query)}
  return <><header className="mb-7"><p className="text-xs font-semibold uppercase tracking-[.2em] text-primary">Platform Yönetimi</p><h2 className="mt-2 text-3xl font-semibold">Abonelik Yönetimi</h2></header>{status&&<p className="mb-4 rounded-xl border p-4 text-sm">{status}</p>}<form onSubmit={activate} className={`${panel} mb-6 grid gap-4 md:grid-cols-3`}><select required name="companyId" className={field}><option value="">Şirket seçin</option>{companies?.map(c=><option key={c.id} value={c.id}>{c.name} · {c.owner.email}</option>)}</select><select name="planSlug" className={field}><option value="starter">Başlangıç</option><option value="professional">Profesyonel</option><option value="enterprise">Kurumsal</option></select><select name="billingPeriod" className={field}><option value="MONTHLY">Aylık</option><option value="YEARLY">Yıllık</option><option value="CUSTOM">Özel dönem</option></select><input required name="startsAt" type="datetime-local" className={field}/><input required name="endsAt" type="datetime-local" className={field}/><select name="paymentMethod" className={field}><option value="MANUAL_BANK_TRANSFER">Banka transferi</option><option value="CASH">Nakit</option><option value="OTHER">Diğer</option></select><input name="currency" defaultValue="TRY" className={field}/><input name="customAmount" type="number" min="0" placeholder="Kurumsal özel tutar" className={field}/><input name="note" placeholder="Not" className={field}/><button className="rounded-xl bg-primary px-4 py-3 font-semibold text-white">Manuel etkinleştir</button></form><section className={panel}><form onSubmit={e=>{e.preventDefault();void load(query)}} className="mb-5 flex gap-2"><label className="flex flex-1 items-center gap-2 rounded-xl border px-3"><Search className="size-4"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Şirket, e-posta veya telefon ara" className="w-full bg-transparent py-3 text-sm outline-none"/></label><button className={button}>Ara</button></form>{!companies?<LoaderCircle className="animate-spin"/>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="py-3">Şirket</th><th>Fatura profili</th><th>Mevcut abonelik</th><th>İşlemler</th></tr></thead><tbody>{companies.map(c=>{const sub=c.subscriptions[0];return <tr key={c.id} className="border-b"><td className="py-4"><b>{c.name}</b><p className="text-xs text-muted">{c.owner.email}</p></td><td>{c.billingProfile?.legalName||"Eksik"}</td><td>{sub?`${sub.plan.name} · ${sub.status}`:"-"}</td><td>{sub&&<div className="flex flex-wrap gap-2"><button onClick={()=>void mutate(sub.id,"extend")} className={button}>Uzat</button><button onClick={()=>void mutate(sub.id,"cancel")} className={button}>İptal</button><button onClick={()=>void mutate(sub.id,"reactivate")} className={button}>Etkinleştir</button></div>}</td></tr>})}</tbody></table></div>}</section></>
}
