"use client";

import { useState } from "react";
import { Boxes, CalendarClock, Check, CircleAlert, Copy, CreditCard, Download, Eye, FileText, Filter, History, MoreHorizontal, Plus, RefreshCw, Search, Send, Smartphone, Sparkles, Upload, UsersRound, Wifi, WifiOff, XCircle } from "lucide-react";
import { useI18n } from "@/i18n/provider";
import { accounts, campaigns, categories, groups } from "@/lib/mock-data";
import { cn } from "@/lib/utils";

const primary = "inline-flex items-center justify-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-[#07130e]";
const ghost = "inline-flex items-center justify-center gap-2 rounded-xl border bg-card px-3 py-2.5 text-sm hover:bg-primary-soft";
function Card({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <section className={cn("panel rounded-2xl", className)}>{children}</section>; }
function Header({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: React.ReactNode }) { return <div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-2 text-[11px] font-semibold uppercase tracking-[.22em] text-primary">{eyebrow}</p><h2 className="text-2xl font-semibold tracking-tight md:text-3xl">{title}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-muted">{description}</p></div>{action}</div>; }
function Status({ children, tone = "green" }: { children: React.ReactNode; tone?: "green" | "red" | "amber" | "blue" }) { const tones = { green: "bg-primary-soft text-primary", red: "bg-red-500/10 text-danger", amber: "bg-amber-500/10 text-amber-500", blue: "bg-blue-500/10 text-blue-500" }; return <span className={cn("inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[11px] font-semibold", tones[tone])}><span className="size-1.5 rounded-full bg-current" />{children}</span>; }
function SectionTitle({ title, hint }: { title: string; hint: string }) { return <div className="flex items-center justify-between"><h3 className="text-sm font-semibold">{title}</h3><span className="text-[11px] text-muted">{hint}</span></div>; }
function Toolbar({ placeholder }: { placeholder: string }) { const { t } = useI18n(); return <Card className="mb-5 flex flex-col gap-3 p-3 sm:flex-row"><label className="flex flex-1 items-center gap-2 rounded-xl border bg-background/50 px-3"><Search className="size-4 text-muted" /><input className="w-full bg-transparent py-2.5 text-sm outline-none" placeholder={placeholder} /></label><button className={ghost}><Filter className="size-4" />{t("common.filters")}</button><button className={ghost}><CalendarClock className="size-4" />{t("common.dateRange")}</button></Card>; }

export function DashboardPage() {
  const { t } = useI18n();
  const metrics = [["dashboard.connectedAccounts", "2 / 3", Smartphone], ["dashboard.groupsContacts", "127 / 2.2k", UsersRound], ["dashboard.sentMonth", "6,420", Send], ["dashboard.failed", "19", CircleAlert]] as const;
  return <><Header eyebrow={t("dashboard.eyebrow")} title={t("dashboard.greeting")} description={t("dashboard.description")} action={<button className={primary}><Send className="size-4" />{t("dashboard.newMessage")}</button>} />
    <Card className="mb-6 p-5"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div className="flex gap-4"><span className="grid size-11 place-items-center rounded-xl bg-primary-soft text-primary"><Sparkles className="size-5" /></span><div><h3 className="font-semibold">{t("trial.professional")}</h3><p className="mt-1 text-sm text-muted">{t("dashboard.trialUsage")}</p></div></div><Status>{t("dashboard.daysRemaining", { count: 2 })}</Status></div></Card>
    <div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([key, value, Icon]) => <Card key={key} className="p-5"><Icon className="mb-6 size-5 text-primary" /><p className="text-xs text-muted">{t(key)}</p><p className="mt-1 font-mono text-2xl font-semibold">{value}</p></Card>)}</div>
    <div className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><Card className="p-5"><SectionTitle title={t("dashboard.performance")} hint={t("dashboard.last7Days")} /><div className="mt-8 flex h-52 items-end gap-3">{[42,65,52,82,61,90,74].map((h,i)=><div key={i} className="flex flex-1 flex-col items-center gap-2"><div className="w-full rounded-t-md bg-gradient-to-t from-emerald-900 to-primary" style={{height:`${h}%`}} /></div>)}</div></Card><Card className="p-5"><SectionTitle title={t("dashboard.categoryDistribution")} hint={t("dashboard.categorizedGroups", { count: 93 })} /><div className="mt-5 space-y-5">{categories.map(c=><div key={c.name}><div className="mb-2 flex justify-between text-xs"><span>{c.name}</span><span className="text-muted">{t("common.groupCount", { count: c.groups })}</span></div><div className="h-1.5 rounded-full bg-foreground/5"><div className="h-full rounded-full" style={{background:c.color,width:`${c.groups*2}%`}} /></div></div>)}</div></Card></div>
    <Card className="mt-6 overflow-hidden"><div className="p-5"><SectionTitle title={t("dashboard.recentCampaigns")} hint={t("dashboard.liveUpdates")} /></div><CampaignTable /></Card>
  </>;
}

export function AccountsPage() {
  const { t } = useI18n(); const [connecting,setConnecting]=useState(false);
  return <><Header eyebrow={t("accounts.eyebrow")} title={t("accounts.title")} description={t("accounts.description")} action={<button className={primary} onClick={()=>setConnecting(true)}><Plus className="size-4" />{t("accounts.add")}</button>} />
    {connecting&&<Card className="mb-6 flex flex-col items-center p-8 text-center"><button className="ms-auto" onClick={()=>setConnecting(false)}><XCircle className="size-5" /></button><Smartphone className="my-5 size-20 text-primary" /><h3 className="font-semibold">{t("accounts.scan")}</h3><p className="mt-2 max-w-md text-sm text-muted">{t("accounts.scanHelp")}</p><Status tone="amber">{t("accounts.waiting")}</Status></Card>}
    <div className="grid gap-5 xl:grid-cols-3">{accounts.map(a=><Card key={a.name} className="p-5"><div className="mb-5 flex justify-between"><span className={cn("grid size-11 place-items-center rounded-xl",a.status==="Connected"?"bg-primary-soft text-primary":"bg-red-500/10 text-danger")}>{a.status==="Connected"?<Wifi/>:<WifiOff/>}</span><MoreHorizontal className="size-4 text-muted" /></div><h3 className="font-semibold">{a.name}</h3><p className="mt-1 font-mono text-xs text-muted">{a.phone}</p><div className="my-5 grid grid-cols-3 gap-2 text-center"><Mini value={a.groups} label={t("common.groups")} /><Mini value={a.contacts} label={t("common.contacts")} /><Mini value={a.sync} label={t("accounts.lastSync")} /></div><button className={cn(ghost,"w-full")}><RefreshCw className="size-4" />{a.status==="Connected"?t("accounts.sync"):t("accounts.reconnect")}</button></Card>)}</div>
  </>;
}
function Mini({value,label}:{value:string|number;label:string}) { return <div><p className="font-mono text-xs font-semibold">{value}</p><p className="mt-1 text-[9px] uppercase text-muted">{label}</p></div>; }

export function GroupsPage() {
  const { t } = useI18n(); const heads=["common.group","common.account","common.members","common.category","common.permission"];
  return <><Header eyebrow={t("groups.eyebrow")} title={t("groups.title")} description={t("groups.description")} action={<button className={ghost}><RefreshCw className="size-4" />{t("groups.syncAll")}</button>} /><Toolbar placeholder={t("groups.search")} /><Card className="overflow-x-auto"><table className="w-full text-start text-sm"><thead className="border-b bg-foreground/[.025] text-[10px] uppercase text-muted"><tr>{heads.map(h=><th className="px-5 py-4 font-medium" key={h}>{t(h)}</th>)}</tr></thead><tbody>{groups.map(g=><tr className="border-b last:border-0" key={g.name}><td className="px-5 py-4 font-medium">{g.name}</td><td className="px-5 py-4 text-muted">{g.account}</td><td className="px-5 py-4">{g.members}</td><td className="px-5 py-4">{g.category}</td><td className="px-5 py-4"><Status tone={g.send?"green":"red"}>{g.send?t("groups.canSend"):t("groups.unavailable")}</Status></td></tr>)}</tbody></table></Card></>;
}

export function CategoriesPage() {
  const { t } = useI18n(); const [added,setAdded]=useState(false);
  return <><Header eyebrow={t("categories.eyebrow")} title={t("categories.title")} description={t("categories.description")} action={<button className={primary} onClick={()=>setAdded(true)}><Plus className="size-4" />{t("categories.new")}</button>} />{added&&<Card className="mb-5 flex justify-between p-4 text-sm"><span>{t("categories.created")}</span><button onClick={()=>setAdded(false)}><XCircle className="size-4" /></button></Card>}<div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">{categories.map(c=><Card key={c.name} className="p-5"><span className="mb-7 block size-3 rounded-full" style={{background:c.color}} /><h3 className="font-semibold">{c.name}</h3><p className="mt-1 text-xs text-muted">{t("categories.segment")}</p><div className="mt-6 flex justify-between border-t pt-4"><Mini value={c.groups} label={t("common.groups")} /><Mini value={c.audience} label={t("common.reach")} /></div></Card>)}</div></>;
}

export function SendMessagePage() {
  const { t } = useI18n(); const [text,setText]=useState(t("composer.sample")); const [sent,setSent]=useState(false);
  return <><Header eyebrow={t("composer.eyebrow")} title={t("composer.title")} description={t("composer.description")} /><div className="grid gap-6 xl:grid-cols-[1.25fr_.75fr]"><div className="space-y-5"><Card className="p-5"><SectionTitle title={t("composer.selectAudiences")} hint={t("composer.step1")} /><div className="mt-4 grid gap-3 sm:grid-cols-2">{categories.map((c,i)=><label key={c.name} className="flex items-center gap-3 rounded-xl border p-3 text-sm"><input type="checkbox" defaultChecked={i<2}/><span>{c.name}</span><span className="ms-auto text-muted">{c.groups}</span></label>)}</div></Card><Card className="p-5"><SectionTitle title={t("composer.write")} hint={t("composer.step2")} /><textarea value={text} onChange={e=>setText(e.target.value)} className="mt-4 min-h-48 w-full rounded-xl border bg-background/50 p-4 text-sm outline-none"/><button className={cn(ghost,"mt-3")}><Upload className="size-4"/>{t("composer.addMedia")}</button></Card><Card className="p-5"><SectionTitle title={t("composer.deliveryMode")} hint={t("composer.step3")} /><div className="mt-4 grid grid-cols-3 gap-3">{["composer.sendNow","composer.schedule","composer.recurring"].map(key=><button className="rounded-xl border p-4 text-sm" key={key}>{t(key)}</button>)}</div></Card></div><Card className="h-fit p-5"><SectionTitle title={t("composer.summary")} hint={t("composer.preview")} /><div className="my-5 rounded-xl bg-[#dff7e8] p-4 text-sm leading-6 text-[#13251b]">{text}</div><p className="mb-4 text-xs text-muted">{t("composer.targets", { count: 62 })}</p><button className={cn(primary,"w-full")} onClick={()=>setSent(true)}><Send className="size-4"/>{sent?t("composer.queued"):t("composer.reviewSend")}</button></Card></div></>;
}

export function HistoryPage() { const {t}=useI18n(); return <><Header eyebrow={t("history.eyebrow")} title={t("history.title")} description={t("history.description")} action={<button className={ghost}><FileText className="size-4"/>{t("history.export")}</button>} /><Toolbar placeholder={t("history.search")} /><Card className="overflow-hidden"><CampaignTable /></Card></>; }
function CampaignTable() { const {t}=useI18n(); return <div className="overflow-x-auto"><table className="w-full text-start text-sm"><thead className="border-b bg-foreground/[.025] text-[10px] uppercase text-muted"><tr>{["history.campaign","common.status","history.progress","history.sentAt",""].map(key=><th key={key} className="px-5 py-4 font-medium">{t(key)}</th>)}</tr></thead><tbody>{campaigns.map(c=><tr key={c.title} className="border-b last:border-0"><td className="px-5 py-4 font-medium">{c.title}</td><td className="px-5 py-4"><Status>{t(`status.${c.status.replaceAll(" ","_").toLowerCase()}`)}</Status></td><td className="px-5 py-4">{t("history.sentFailed",{sent:c.sent,failed:c.failed})}</td><td className="px-5 py-4 text-muted">{c.time}</td><td className="px-5 py-4"><div className="flex gap-1"><button className={ghost}><Eye className="size-3"/></button><button className={ghost}><Copy className="size-3"/></button></div></td></tr>)}</tbody></table></div>; }

export function SettingsPage() {
  const {t}=useI18n(); const [section,setSection]=useState<"company"|"billing">("company"); const [saved,setSaved]=useState(false);
  return <><Header eyebrow={t("settings.eyebrow")} title={t("settings.title")} description={t("settings.description")} /><div className="grid gap-6 xl:grid-cols-[240px_1fr]"><Card className="h-fit p-3">{[["company",Boxes],["billing",CreditCard],["users",UsersRound],["notifications",CircleAlert],["danger",History]].map(([key,Icon])=><button key={key as string} onClick={()=> (key==="company"||key==="billing")&&setSection(key)} className={cn("flex w-full items-center gap-3 rounded-xl px-3 py-3 text-start text-sm text-muted",section===key&&"bg-primary-soft text-primary")}><Icon className="size-4"/>{t(`settings.${key}`)}</button>)}</Card>{section==="company"?<BillingForm saved={saved} onSave={()=>setSaved(true)}/>:<BillingOverview onEdit={()=>setSection("company")}/>}</div></>;
}
function BillingForm({saved,onSave}:{saved:boolean;onSave:()=>void}) { const {t}=useI18n(); const fields=["companyName","legalName","tradeName","taxOffice","taxNumber","country","city","district","postalCode","billingEmail","billingPhone","invoiceType"]; return <Card className="p-6"><SectionTitle title={t("billing.profile")} hint={saved?t("billing.complete"):t("billing.needsReview")} /><div className="mt-6 grid gap-5 sm:grid-cols-2">{fields.map(key=><label key={key}><span className="mb-2 block text-xs font-medium">{t(`billing.${key}`)}</span><input className="w-full rounded-xl border bg-background/50 px-3 py-3 text-sm outline-none" /></label>)}<label className="sm:col-span-2"><span className="mb-2 block text-xs font-medium">{t("billing.address")}</span><textarea className="min-h-24 w-full rounded-xl border bg-background/50 p-3"/></label></div><button className={cn(primary,"mt-6")} onClick={onSave}><Check className="size-4"/>{t("billing.save")}</button></Card>; }
function BillingOverview({onEdit}:{onEdit:()=>void}) { const {t}=useI18n(); return <div className="space-y-5"><Card className="p-5"><SectionTitle title={t("billing.currentPlan")} hint={t("billing.paymentStatus")} /><h3 className="mt-5 text-xl font-semibold">{t("plans.professional")}</h3><button className={cn(primary,"mt-5")}>{t("billing.upgrade")}</button></Card><Card className="p-5"><SectionTitle title={t("billing.invoiceHistory")} hint={t("billing.providerNotice")} /><button className={cn(ghost,"mt-5")} onClick={onEdit}>{t("billing.update")}</button><button className={cn(ghost,"mt-5 ms-2")}><Download className="size-4"/>{t("billing.downloadPdf")}</button></Card></div>; }
