"use client";
/* eslint-disable react-hooks/set-state-in-effect, @typescript-eslint/no-explicit-any */
import { FormEvent, useCallback, useEffect, useState } from "react";
import { Activity, Building2, CheckCircle2, CircleHelp, Database, HeartPulse, LoaderCircle, MessageSquare, Plus, Send, ShieldAlert, Users } from "lucide-react";
import { useI18n } from "@/i18n/provider";

const panel="panel rounded-2xl p-5",button="rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50",field="w-full rounded-xl border bg-white px-3 py-3 text-sm outline-none";
function Loading(){return <div className="grid min-h-60 place-items-center"><LoaderCircle className="animate-spin text-primary"/></div>}
function Header({title,description,eyebrow}:{title:string;description:string;eyebrow?:string}){const{locale}=useI18n();return <header className="mb-7"><p className="text-xs font-semibold uppercase tracking-[.2em] text-primary">{eyebrow??(locale==="tr"?"Logivya Operasyonları":"Logivya Operations")}</p><h1 className="mt-2 text-3xl font-semibold">{title}</h1><p className="mt-2 text-sm text-muted">{description}</p></header>}
function Metric({label,value,Icon}:{label:string;value:string|number;Icon:typeof Activity}){return <div className={panel}><Icon className="mb-5 size-5 text-primary"/><p className="text-xs text-muted">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div>}

export function SupportPage(){const[tickets,setTickets]=useState<any[]|null>(null),[status,setStatus]=useState("");const load=useCallback(async()=>{const r=await fetch("/api/support/tickets");setTickets((await r.json()).tickets||[])},[]);useEffect(()=>{void load()},[load]);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget),r=await fetch("/api/support/tickets",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(form))});setStatus(r.ok?"Destek talebiniz oluşturuldu.":"Talep oluşturulamadı.");if(r.ok){e.currentTarget.reset();void load()}}return <><Header title="Destek Merkezi" description="Teknik, ödeme ve WhatsApp bağlantı sorunlarını Logivya ekibine iletin."/><form onSubmit={submit} className={`${panel} mb-6 grid gap-3 md:grid-cols-2`}><input required name="subject" placeholder="Konu" className={field}/><select name="type" className={field}>{["WhatsApp bağlantı sorunu","QR kod sorunu","Mesaj gönderim sorunu","Abonelik / ödeme","Fatura","Teknik hata","Diğer"].map(x=><option key={x}>{x}</option>)}</select><select name="priority" className={field}><option value="LOW">Düşük</option><option value="MEDIUM">Orta</option><option value="HIGH">Yüksek</option><option value="URGENT">Acil</option></select><textarea required name="message" placeholder="Sorununuzu açıklayın" className={`${field} min-h-28 md:col-span-2`}/><button className={button}><Plus className="me-2 inline size-4"/>Talep oluştur</button>{status&&<p className="self-center text-sm text-muted">{status}</p>}</form>{!tickets?<Loading/>:<div className="grid gap-4">{tickets.map(t=><article key={t.id} className={panel}><div className="flex justify-between gap-4"><div><h3 className="font-semibold">{t.subject}</h3><p className="mt-1 text-xs text-muted">{t.type} · {t.createdBy.name}</p></div><span className="h-fit rounded-full bg-primary-soft px-3 py-1 text-xs font-semibold text-primary">{t.status}</span></div><p className="mt-4 text-sm text-muted">{t.messages[0]?.message}</p></article>)}</div>}</>}

export function ActivityPage(){const[logs,setLogs]=useState<any[]|null>(null);useEffect(()=>{void fetch("/api/activity").then(r=>r.json()).then(v=>setLogs(v.logs||[]))},[]);return <><Header title="Aktivite Merkezi" description="Çalışma alanınızdaki güvenlik ve operasyon hareketlerini inceleyin."/>{!logs?<Loading/>:<div className={panel}>{logs.map(log=><div key={log.id} className="flex gap-4 border-b py-4 last:border-0"><Activity className="mt-1 size-4 text-primary"/><div><b className="text-sm">{log.action}</b><p className="text-xs text-muted">{log.entityType} · {log.user?.name||"Sistem"} · {new Date(log.createdAt).toLocaleString()}</p></div></div>)}</div>}</>}

export function OnboardingPage(){const[data,setData]=useState<any>();useEffect(()=>{void fetch("/api/onboarding").then(r=>r.json()).then(v=>setData(v.onboarding))},[]);if(!data)return <Loading/>;const items=[["Şirket bilgilerini tamamla",data.companyProfileCompleted,"/settings/company"],["WhatsApp hesabı bağla",data.whatsappConnected,"/accounts"],["Grupları senkronize et",data.groupsSynced,"/groups"],["İlk kategoriyi oluştur",data.categoryCreated,"/categories"],["İlk test mesajını gönder",data.firstMessageSent,"/send-message"]] as const;const progress=Math.round(items.filter(x=>x[1]).length/items.length*100);return <><Header title="Logivya'ya Hoş Geldiniz" description="İlk mesaj operasyonunuzu birkaç adımda hazır hale getirin."/><div className={`${panel} mb-5`}><div className="flex justify-between text-sm"><b>Kurulum ilerlemesi</b><span>{progress}%</span></div><div className="mt-3 h-2 rounded-full bg-primary-soft"><div className="h-full rounded-full bg-primary" style={{width:`${progress}%`}}/></div></div><div className="grid gap-3">{items.map(([label,done,href])=><a key={label} href={href} className={`${panel} flex items-center gap-4 hover:border-primary`}><CheckCircle2 className={done?"text-green-600":"text-muted"}/><span className="font-medium">{label}</span><span className="ms-auto text-xs text-muted">{done?"Tamamlandı":"Devam et"}</span></a>)}</div></>}

export function AdminDashboardPage(){const{locale}=useI18n();const isTr=locale==="tr";const[data,setData]=useState<any>();useEffect(()=>{void fetch("/api/admin/dashboard").then(r=>r.json()).then(setData)},[]);if(!data)return <Loading/>;const m=data.metrics||{};return <><Header eyebrow={isTr?"Logivya Operasyonları":"Logivya Operations"} title={isTr?"Yönetici Kontrol Merkezi":"Admin Command Center"} description={isTr?"Müşteriler, abonelikler, destek ve platform sağlığının merkezi görünümü.":"Central view of customers, subscriptions, support, and platform health."}/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label={isTr?"Toplam şirket":"Total companies"} value={m.companies||0} Icon={Building2}/><Metric label={isTr?"Toplam kullanıcı":"Total users"} value={m.users||0} Icon={Users}/><Metric label={isTr?"Bekleyen abonelik talebi":"Pending subscription requests"} value={m.pendingSubscriptionRequests||0} Icon={Activity}/><Metric label={isTr?"Aktif abonelik":"Active subscriptions"} value={m.activeSubscriptions||0} Icon={CheckCircle2}/><Metric label={isTr?"Deneme hesabı":"Trial accounts"} value={m.trials||0} Icon={Activity}/><Metric label={isTr?"7 gün içinde bitecek":"Expiring in 7 days"} value={m.expiringInSevenDays||0} Icon={Activity}/><Metric label={isTr?"Bu ay onaylanan ödeme":"Approved payments this month"} value={`${m.monthlyConfirmedPaymentTotal||0} TRY`} Icon={Activity}/><Metric label={isTr?"Bağlı WhatsApp":"Connected WhatsApp"} value={`${m.connected||0} / ${m.accounts||0}`} Icon={MessageSquare}/><Metric label={isTr?"Toplam kampanya":"Total campaigns"} value={m.campaigns||0} Icon={Send}/><Metric label={isTr?"Toplam mesaj":"Total messages"} value={m.messages||0} Icon={MessageSquare}/></div></>}

export function AdminListPage({title,endpoint,kind}:{title:string;endpoint:string;kind:string}){const[data,setData]=useState<any>();useEffect(()=>{void fetch(endpoint).then(r=>r.json()).then(setData)},[endpoint]);const rows=data?.[kind]||[];return <><Header title={title} description="Platform genelindeki kayıtları güvenli yönetim görünümünde inceleyin."/>{!data?<Loading/>:<div className={`${panel} overflow-x-auto`}><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="py-3">Kayıt</th><th>Durum</th><th>Şirket / kullanıcı</th><th>Tarih</th></tr></thead><tbody>{rows.map((row:any)=><tr key={row.id} className="border-b last:border-0"><td className="py-4 font-medium">{row.subject||row.action||row.type||row.invoiceNumber||row.id}</td><td>{row.status||row.severity||"-"}</td><td>{row.company?.name||row.createdBy?.email||row.user?.email||"-"}</td><td>{new Date(row.createdAt||row.lastMessageAt).toLocaleString()}</td></tr>)}</tbody></table>{!rows.length&&<p className="py-12 text-center text-sm text-muted">Kayıt bulunmuyor.</p>}</div>}</>}

export function SystemHealthPage(){const[data,setData]=useState<any>();useEffect(()=>{void fetch("/api/admin/system/health").then(r=>r.json()).then(setData)},[]);if(!data)return <Loading/>;return <><Header title="Sistem Sağlığı" description="Uygulama, veritabanı, queue, storage ve e-posta sağlayıcı durumları."/><div className="grid gap-4 md:grid-cols-3"><Metric label="Uygulama" value={data.app||"unknown"} Icon={HeartPulse}/><Metric label="Veritabanı" value={data.database?.status||"unknown"} Icon={Database}/><Metric label="Queue başarısız işler" value={data.queue?.counts?.failed||0} Icon={ShieldAlert}/><Metric label="Worker" value={data.worker||"unknown"} Icon={Activity}/><Metric label="Storage" value={data.storage||"unknown"} Icon={Database}/><Metric label="E-posta" value={data.email||"unknown"} Icon={CircleHelp}/></div></>}
export function AdminMetricsPage(){const[data,setData]=useState<any>();useEffect(()=>{void fetch("/api/admin/metrics").then(r=>r.json()).then(v=>setData(v.metrics))},[]);if(!data)return <Loading/>;return <><Header title="SaaS Metrikleri" description="Büyüme, kullanım ve abonelik performansının yönetim görünümü."/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{Object.entries(data).map(([key,value])=><Metric key={key} label={key} value={value===null?"Hazırlanıyor":String(value)} Icon={Activity}/>)}</div></>}
