const keys = ["description", "contactRequired", "continueAccount", "contactAdvertiser", "trial", "registerTrial", "loadError", "empty", "more", "expired", "openMenu", "closeMenu", "services", "quickActions", "filterListings"] as const;
const copy: Record<string, readonly string[]> = {
  tr: ["Yük, araç ve şoför ilanlarını keşfedin.", "İletişim için kayıt ve geçerli deneme veya abonelik gerekir.", "Hesabınızla devam edin", "İletişim için hesabınızla devam edin", "Kayıt olduktan sonra 7 gün ücretsiz deneyin. İletişim özellikleri geçerli deneme veya abonelik ile açılır.", "Kayıt ol · 7 gün ücretsiz", "İlanlar yüklenemedi. Yeniden deneyin.", "Bu filtrelere uygun ilan bulunamadı.", "Daha fazla ilan", "İlan bulunamadı veya süresi doldu.", "Menüyü aç", "Menüyü kapat", "Hizmetler", "Hızlı işlemler", "İlanları filtrele"],
  en: ["Explore freight, vehicle and driver listings.", "Contact requires registration and an active trial or subscription.", "Continue with your account", "Sign in to contact the advertiser", "Try free for 7 days after registering. Contact requires an active trial or subscription.", "Register · 7 days free", "Unable to load listings. Please retry.", "No listings match these filters.", "More listings", "This listing was not found or has expired.", "Open menu", "Close menu", "Services", "Quick actions", "Filter listings"],
  ar: ["اكتشف إعلانات الشحن والمركبات والسائقين.", "يتطلب التواصل التسجيل وفترة تجريبية أو اشتراكًا ساريًا.", "تابع باستخدام حسابك", "سجّل الدخول للتواصل مع المعلن", "جرّب مجانًا لمدة 7 أيام بعد التسجيل. يتطلب التواصل فترة تجريبية أو اشتراكًا ساريًا.", "سجّل · 7 أيام مجانًا", "تعذّر تحميل الإعلانات. حاول مجددًا.", "لا توجد إعلانات تطابق هذه المرشحات.", "المزيد من الإعلانات", "لم يتم العثور على الإعلان أو انتهت صلاحيته.", "فتح القائمة", "إغلاق القائمة", "الخدمات", "إجراءات سريعة", "تصفية الإعلانات"],
  ro: ["Descoperiți anunțuri de marfă, vehicule și șoferi.", "Contactul necesită înregistrare și o perioadă de probă sau un abonament activ.", "Continuați cu contul dvs.", "Autentificați-vă pentru a contacta autorul", "Încercați gratuit 7 zile după înregistrare. Contactul necesită o perioadă de probă sau un abonament activ.", "Înregistrare · 7 zile gratuit", "Anunțurile nu au putut fi încărcate. Reîncercați.", "Niciun anunț nu corespunde filtrelor.", "Mai multe anunțuri", "Anunțul nu a fost găsit sau a expirat.", "Deschide meniul", "Închide meniul", "Servicii", "Acțiuni rapide", "Filtrează anunțurile"],
  ru: ["Просматривайте объявления о грузах, транспорте и водителях.", "Для связи нужны регистрация и действующий пробный период или подписка.", "Продолжить с вашим аккаунтом", "Войдите, чтобы связаться с автором", "После регистрации — 7 дней бесплатно. Для связи нужен действующий пробный период или подписка.", "Регистрация · 7 дней бесплатно", "Не удалось загрузить объявления. Повторите попытку.", "По этим фильтрам объявлений нет.", "Больше объявлений", "Объявление не найдено или срок истёк.", "Открыть меню", "Закрыть меню", "Услуги", "Быстрые действия", "Фильтр объявлений"],
  az: ["Yük, nəqliyyat vasitəsi və sürücü elanlarını kəşf edin.", "Əlaqə üçün qeydiyyat və aktiv sınaq müddəti və ya abunəlik tələb olunur.", "Hesabınızla davam edin", "Elan sahibi ilə əlaqə üçün daxil olun", "Qeydiyyatdan sonra 7 gün pulsuz sınayın. Əlaqə üçün aktiv sınaq müddəti və ya abunəlik tələb olunur.", "Qeydiyyat · 7 gün pulsuz", "Elanlar yüklənmədi. Yenidən cəhd edin.", "Bu filtrlərə uyğun elan tapılmadı.", "Daha çox elan", "Elan tapılmadı və ya müddəti bitib.", "Menyunu aç", "Menyunu bağla", "Xidmətlər", "Sürətli əməliyyatlar", "Elanları filtrlə"],
  tk: ["Ýük, ulag we sürüji bildirişlerini gözden geçiriň.", "Habarlaşmak üçin hasaba alyş we işjeň synag möhleti ýa-da abuna gerek.", "Hasabyňyz bilen dowam ediň", "Bildiriş eýesi bilen habarlaşmak üçin giriň", "Hasaba alnanyňyzdan soň 7 gün mugt synap görüň. Habarlaşmak üçin işjeň synag möhleti ýa-da abuna gerek.", "Hasaba al · 7 gün mugt", "Bildirişler ýüklenmedi. Gaýtadan synanyşyň.", "Bu süzgüçlere laýyk bildiriş tapylmady.", "Has köp bildiriş", "Bildiriş tapylmady ýa-da möhleti gutardy.", "Menýuny aç", "Menýuny ýap", "Hyzmatlar", "Çalt amallar", "Bildirişleri süz"],
  de: ["Entdecken Sie Fracht-, Fahrzeug- und Fahreranzeigen.", "Für die Kontaktaufnahme sind eine Registrierung und eine aktive Testphase oder ein Abonnement erforderlich.", "Mit Ihrem Konto fortfahren", "Anmelden, um den Anbieter zu kontaktieren", "Nach der Registrierung 7 Tage kostenlos testen. Für die Kontaktaufnahme ist eine aktive Testphase oder ein Abonnement erforderlich.", "Registrieren · 7 Tage kostenlos", "Anzeigen konnten nicht geladen werden. Bitte erneut versuchen.", "Keine Anzeigen entsprechen diesen Filtern.", "Weitere Anzeigen", "Die Anzeige wurde nicht gefunden oder ist abgelaufen.", "Menü öffnen", "Menü schließen", "Dienste", "Schnellaktionen", "Anzeigen filtern"],
  bg: ["Разгледайте обяви за товари, превозни средства и шофьори.", "За контакт са необходими регистрация и активен пробен период или абонамент.", "Продължете с профила си", "Влезте, за да се свържете с подателя", "Изпробвайте безплатно 7 дни след регистрация. За контакт е необходим активен пробен период или абонамент.", "Регистрация · 7 дни безплатно", "Обявите не бяха заредени. Опитайте отново.", "Няма обяви, съответстващи на филтрите.", "Още обяви", "Обявата не е намерена или е изтекла.", "Отвори менюто", "Затвори менюто", "Услуги", "Бързи действия", "Филтрирай обявите"],
  el: ["Ανακαλύψτε αγγελίες φορτίων, οχημάτων και οδηγών.", "Η επικοινωνία απαιτεί εγγραφή και ενεργή δοκιμή ή συνδρομή.", "Συνεχίστε με τον λογαριασμό σας", "Συνδεθείτε για να επικοινωνήσετε με τον διαφημιζόμενο", "Δοκιμάστε δωρεάν για 7 ημέρες μετά την εγγραφή. Η επικοινωνία απαιτεί ενεργή δοκιμή ή συνδρομή.", "Εγγραφή · 7 ημέρες δωρεάν", "Δεν ήταν δυνατή η φόρτωση των αγγελιών. Δοκιμάστε ξανά.", "Δεν υπάρχουν αγγελίες για αυτά τα φίλτρα.", "Περισσότερες αγγελίες", "Η αγγελία δεν βρέθηκε ή έχει λήξει.", "Άνοιγμα μενού", "Κλείσιμο μενού", "Υπηρεσίες", "Γρήγορες ενέργειες", "Φιλτράρισμα αγγελιών"],
  uz: ["Yuk, transport va haydovchi e’lonlarini ko‘rib chiqing.","Bog‘lanish uchun ro‘yxatdan o‘tish va amaldagi sinov muddati yoki obuna talab qilinadi.","Hisobingiz orqali davom eting","E’lon egasi bilan bog‘lanish uchun hisobingizga kiring","Ro‘yxatdan o‘tgach, 7 kun bepul sinab ko‘ring. Bog‘lanish uchun amaldagi sinov muddati yoki obuna kerak.","Ro‘yxatdan o‘tish · 7 kun bepul","E’lonlar yuklanmadi. Qayta urinib ko‘ring.","Bu filtrlarga mos e’lon topilmadi.","Ko‘proq e’lonlar","E’lon topilmadi yoki uning muddati tugagan.","Menyuni ochish","Menyuni yopish","Xizmatlar","Tezkor amallar","E’lonlarni filtrlash"],
  sr: ["Istražite oglase za teret, vozila i vozače.", "Za kontakt su potrebni registracija i aktivan probni period ili pretplata.", "Nastavite sa svojim nalogom", "Prijavite se da kontaktirate oglašivača", "Isprobajte besplatno 7 dana nakon registracije. Za kontakt je potreban aktivan probni period ili pretplata.", "Registracija · 7 dana besplatno", "Oglasi nisu učitani. Pokušajte ponovo.", "Nema oglasa koji odgovaraju filterima.", "Još oglasa", "Oglas nije pronađen ili je istekao.", "Otvori meni", "Zatvori meni", "Usluge", "Brze radnje", "Filtriraj oglase"],
};
export function guestMarketplaceCopy(locale: string) {
  const values = copy[locale] ?? copy.en!;
  return Object.fromEntries(keys.map((key, index) => [key, values[index]!])) as Record<(typeof keys)[number], string>;
}

import generatedLabels from "./guest-marketplace-labels.json";
import { publicMarketplaceSection } from "./public-marketplace-sections";
export function guestMarketplaceLabels(locale: string): { labels: Record<string, string>; descriptions: Record<string, string> } {
  return (generatedLabels as Record<string, { labels: Record<string, string>; descriptions: Record<string, string> }>)[locale] ?? generatedLabels.en;
}
export function guestSectionDescription(locale: string, id: string) {
  const section = publicMarketplaceSection(id);
  if (locale === "tr") return section.description;
  if (locale === "en") return section.english;
  if (id === "overview") return guestMarketplaceCopy(locale).description;
  return guestMarketplaceLabels(locale).descriptions[id] ?? guestMarketplaceCopy(locale).trial;
}
