const keys = ["edit","pause","resume","complete","viewMatches","more","dismiss","save","saved","noMatches","contactRequired","subscribe","registerTrial","login","call","cancel","contactMissing","location","licenses","employment","driverAvailable","driverWanted","adr","international","all","apply","clear","originCountry","destinationCountry","originCity","destinationCity","vehicle","close","filters","openError","callAdvertiser"] as const;
const rows = {
  tr: "Düzenle|Duraklat|Devam et|Tamamla|Eşleşmeleri gör|Daha fazla|İlgilenmiyorum|Kaydet|Kaydedildi|Henüz eşleşme yok.|İletişim için geçerli deneme veya abonelik gerekir.|Aboneliği görüntüle|Kayıt ol · 7 gün ücretsiz|Giriş yap|Ara|Vazgeç|İletişim bilgisi belirtilmedi.|Konum|Ehliyet sınıfları|Çalışma biçimi|Şoför iş arıyor|Şoför aranıyor|ADR gerekli|Uluslararası|Tümü|Uygula|Temizle|Kalkış ülkesi|Varış ülkesi|Kalkış şehri / ilçesi|Varış şehri / ilçesi|Araç tipi|Kapat|İlan filtreleri|Bağlantı açılamadı.|İlan vereni ara",
  en: "Edit|Pause|Resume|Complete|View matches|Load more|Not interested|Save|Saved|No matches yet.|Contact requires an active trial or subscription.|View subscription|Register · 7 days free|Sign in|Call|Cancel|No contact details provided.|Location|Licence classes|Employment type|Driver available|Driver wanted|ADR required|International|All|Apply|Clear|Origin country|Destination country|Origin city / district|Destination city / district|Vehicle type|Close|Listing filters|Could not open the link.|Call advertiser",
  ar: "تعديل|إيقاف مؤقت|متابعة|إكمال|عرض التطابقات|عرض المزيد|غير مهتم|حفظ|تم الحفظ|لا توجد تطابقات بعد.|يتطلب الاتصال فترة تجريبية أو اشتراكًا ساريًا.|عرض الاشتراك|التسجيل · 7 أيام مجانية|تسجيل الدخول|اتصال|إلغاء|لم تُحدد معلومات الاتصال.|الموقع|فئات الرخص|نمط العمل|سائق يبحث عن عمل|مطلوب سائق|مطلوب ADR|دولي|الكل|تطبيق|مسح|بلد الانطلاق|بلد الوجهة|مدينة / منطقة الانطلاق|مدينة / منطقة الوجهة|نوع المركبة|إغلاق|تصفية الإعلانات|تعذر فتح الرابط.|الاتصال بالمعلن",
  uz: "Tahrirlash|Pauza|Davom ettirish|Yakunlash|Mosliklarni ko‘rish|Yana yuklash|Qiziqmayman|Saqlash|Saqlandi|Hozircha moslik yo‘q.|Bog‘lanish uchun amaldagi sinov muddati yoki obuna kerak.|Obunani ko‘rish|Ro‘yxatdan o‘tish · 7 kun bepul|Kirish|Qo‘ng‘iroq|Bekor qilish|Bog‘lanish ma’lumoti ko‘rsatilmagan.|Joylashuv|Guvohnoma toifalari|Ish turi|Haydovchi ish qidiryapti|Haydovchi kerak|ADR kerak|Xalqaro|Barchasi|Qo‘llash|Tozalash|Jo‘nash mamlakati|Borish mamlakati|Jo‘nash shahri / tumani|Borish shahri / tumani|Transport turi|Yopish|E’lon filtrlari|Havolani ochib bo‘lmadi.|E’lon beruvchiga qo‘ng‘iroq",
  de: "Bearbeiten|Pausieren|Fortsetzen|Abschließen|Treffer ansehen|Mehr laden|Kein Interesse|Speichern|Gespeichert|Noch keine Treffer.|Kontakt erfordert einen aktiven Testzeitraum oder ein Abonnement.|Abonnement ansehen|Registrieren · 7 Tage kostenlos|Anmelden|Anrufen|Abbrechen|Keine Kontaktdaten angegeben.|Standort|Führerscheinklassen|Beschäftigungsart|Fahrer sucht Arbeit|Fahrer gesucht|ADR erforderlich|International|Alle|Anwenden|Zurücksetzen|Abgangsland|Zielland|Abgangsort / Bezirk|Zielort / Bezirk|Fahrzeugtyp|Schließen|Anzeigenfilter|Link konnte nicht geöffnet werden.|Inserenten anrufen",
  ru: "Изменить|Приостановить|Продолжить|Завершить|Посмотреть совпадения|Загрузить ещё|Не интересует|Сохранить|Сохранено|Совпадений пока нет.|Для связи нужен действующий пробный период или подписка.|Посмотреть подписку|Регистрация · 7 дней бесплатно|Войти|Позвонить|Отмена|Контактные данные не указаны.|Местоположение|Категории прав|Тип занятости|Водитель ищет работу|Требуется водитель|Требуется ADR|Международные|Все|Применить|Сбросить|Страна отправления|Страна назначения|Город / район отправления|Город / район назначения|Тип транспорта|Закрыть|Фильтры объявлений|Не удалось открыть ссылку.|Позвонить автору объявления",
  ro: "Editează|Pauză|Continuă|Finalizează|Vezi potrivirile|Încarcă mai multe|Nu mă interesează|Salvează|Salvat|Încă nu există potriviri.|Contactul necesită o perioadă de probă sau un abonament activ.|Vezi abonamentul|Înregistrare · 7 zile gratuite|Autentificare|Sună|Anulează|Nu sunt furnizate date de contact.|Locație|Categorii permis|Tip de angajare|Șofer disponibil|Se caută șofer|ADR necesar|Internațional|Toate|Aplică|Resetează|Țara de plecare|Țara de destinație|Oraș / district de plecare|Oraș / district de destinație|Tip vehicul|Închide|Filtre anunțuri|Linkul nu a putut fi deschis.|Sună autorul anunțului",
  az: "Redaktə et|Dayandır|Davam et|Tamamla|Uyğunluqları gör|Daha çox|Maraqlanmıram|Yadda saxla|Saxlanıldı|Hələ uyğunluq yoxdur.|Əlaqə üçün aktiv sınaq müddəti və ya abunəlik lazımdır.|Abunəliyə bax|Qeydiyyat · 7 gün pulsuz|Daxil ol|Zəng et|Ləğv et|Əlaqə məlumatı göstərilməyib.|Məkan|Sürücülük vəsiqəsi kateqoriyaları|İş forması|Sürücü iş axtarır|Sürücü axtarılır|ADR tələb olunur|Beynəlxalq|Hamısı|Tətbiq et|Təmizlə|Çıxış ölkəsi|Təyinat ölkəsi|Çıxış şəhəri / rayonu|Təyinat şəhəri / rayonu|Nəqliyyat növü|Bağla|Elan filtrləri|Keçidi açmaq mümkün olmadı.|Elan verənə zəng et",
  tk: "Üýtget|Saklat|Dowam et|Tamamla|Gabat gelýänleri gör|Has köp|Gyzyklanmaýaryn|Ýatda sakla|Saklandy|Entek gabat gelme ýok.|Habarlaşmak üçin işjeň synag möhleti ýa-da abunalyk gerek.|Abunalygy gör|Hasaba al · 7 gün mugt|Gir|Jaň et|Ýatyr|Habarlaşmak maglumatlary görkezilmedi.|Ýerleşýän ýeri|Sürüjilik şahadatnamasynyň derejeleri|Iş görnüşi|Sürüji iş gözleýär|Sürüji gerek|ADR gerek|Halkara|Hemmesi|Ulan|Arassala|Ugradylýan ýurt|Barylýan ýurt|Ugradylýan şäher / etrap|Barylýan şäher / etrap|Ulag görnüşi|Ýap|Bildiriş süzgüçleri|Salgy açylmady.|Bildiriş eýesine jaň et",
  bg: "Редактиране|Пауза|Продължаване|Завършване|Виж съвпаденията|Зареди още|Не се интересувам|Запази|Запазено|Все още няма съвпадения.|За контакт е нужен активен пробен период или абонамент.|Виж абонамента|Регистрация · 7 дни безплатно|Вход|Обади се|Отказ|Няма посочени данни за контакт.|Местоположение|Категории книжка|Вид заетост|Шофьор търси работа|Търси се шофьор|Изисква се ADR|Международен|Всички|Приложи|Изчисти|Държава на отпътуване|Държава на пристигане|Град / район на отпътуване|Град / район на пристигане|Вид превозно средство|Затвори|Филтри за обяви|Връзката не може да се отвори.|Обади се на подателя",
  el: "Επεξεργασία|Παύση|Συνέχεια|Ολοκλήρωση|Προβολή αντιστοιχιών|Περισσότερα|Δεν ενδιαφέρομαι|Αποθήκευση|Αποθηκεύτηκε|Δεν υπάρχουν ακόμη αντιστοιχίες.|Η επικοινωνία απαιτεί ενεργή δοκιμή ή συνδρομή.|Προβολή συνδρομής|Εγγραφή · 7 ημέρες δωρεάν|Σύνδεση|Κλήση|Ακύρωση|Δεν παρέχονται στοιχεία επικοινωνίας.|Τοποθεσία|Κατηγορίες άδειας|Τύπος απασχόλησης|Οδηγός αναζητά εργασία|Ζητείται οδηγός|Απαιτείται ADR|Διεθνές|Όλα|Εφαρμογή|Εκκαθάριση|Χώρα αναχώρησης|Χώρα προορισμού|Πόλη / περιοχή αναχώρησης|Πόλη / περιοχή προορισμού|Τύπος οχήματος|Κλείσιμο|Φίλτρα αγγελιών|Δεν ήταν δυνατό το άνοιγμα του συνδέσμου.|Κλήση στον διαφημιζόμενο",
  sr: "Izmeni|Pauziraj|Nastavi|Završi|Pogledaj poklapanja|Učitaj još|Ne zanima me|Sačuvaj|Sačuvano|Još nema poklapanja.|Za kontakt je potreban aktivan probni period ili pretplata.|Pogledaj pretplatu|Registracija · 7 dana besplatno|Prijava|Pozovi|Otkaži|Kontakt podaci nisu navedeni.|Lokacija|Kategorije dozvole|Vrsta zaposlenja|Vozač traži posao|Traži se vozač|Potreban ADR|Međunarodno|Sve|Primeni|Obriši|Zemlja polaska|Zemlja odredišta|Grad / okrug polaska|Grad / okrug odredišta|Vrsta vozila|Zatvori|Filteri oglasa|Nije moguće otvoriti vezu.|Pozovi oglašivača",
} as const;
export function productJourneyCopy(locale: string): Record<typeof keys[number], string> {
  const values = (rows[locale as keyof typeof rows] ?? rows.en).split("|");
  return Object.fromEntries(keys.map((key,index) => [key, values[index]])) as Record<typeof keys[number],string>;
}
export function validateProductJourneyCopy() { return Object.entries(rows).every(([,row]) => row.split("|").length === keys.length && row.split("|").every(Boolean)); }
