const rows: Record<string, string> = {
 tr: "Sohbetler|Kanal|Özel sohbet|Telegram oturumu kapatılacak ve bu hesap Logivya’da arşivlenecek.|Gönderilmiş mesajlar Telegram’daki tüm alıcılardan silinecek. Bu işlem geri alınamaz.|Paketiniz gereği mesaj sonuna Logivya tanıtım imzası eklenir.|Mesaj ve tanıtım imzası Telegram sınırını aşıyor. Metni kısaltın.|Sohbet veya kanal ara|Kategori seçip atanacak sohbetleri işaretleyin.|Henüz Telegram gönderimi yok.",
 en: "Chats|Channel|Private chat|The Telegram session will close and this account will be archived in Logivya.|Sent messages will be deleted for all Telegram recipients. This cannot be undone.|Your plan adds a Logivya attribution at the end of the message.|The message and attribution exceed Telegram’s limit. Shorten the text.|Search chats or channels|Choose a category, then select the chats to assign.|No Telegram deliveries yet.",
 ar: "المحادثات|قناة|محادثة خاصة|ستُغلق جلسة تيليجرام وستتم أرشفة الحساب في Logivya.|ستُحذف الرسائل المرسلة لدى جميع المستلمين في تيليجرام. لا يمكن التراجع عن ذلك.|تُضاف عبارة تعريفية بـ Logivya في نهاية الرسالة وفقًا لباقتك.|تتجاوز الرسالة والعبارة التعريفية حد تيليجرام. اختصر النص.|ابحث عن محادثة أو قناة|اختر فئة ثم حدد المحادثات لإسنادها.|لا توجد إرساليات تيليجرام بعد.",
 uz: "Chatlar|Kanal|Shaxsiy chat|Telegram seansi yopiladi va hisob Logivya’da arxivlanadi.|Yuborilgan xabarlar barcha Telegram oluvchilaridan o‘chiriladi. Buni ortga qaytarib bo‘lmaydi.|Tarifingizga ko‘ra xabar oxiriga Logivya tanishtiruv yozuvi qo‘shiladi.|Xabar va tanishtiruv yozuvi Telegram chegarasidan oshmoqda. Matnni qisqartiring.|Chat yoki kanal qidirish|Toifani tanlang, keyin biriktiriladigan chatlarni belgilang.|Hali Telegram yuborishlari yo‘q.",
 de: "Chats|Kanal|Privater Chat|Die Telegram-Sitzung wird beendet und dieses Konto in Logivya archiviert.|Gesendete Nachrichten werden bei allen Telegram-Empfängern gelöscht. Dies lässt sich nicht rückgängig machen.|Ihr Tarif fügt am Nachrichtenende einen Logivya-Hinweis hinzu.|Nachricht und Hinweis überschreiten das Telegram-Limit. Kürzen Sie den Text.|Chats oder Kanäle suchen|Wählen Sie eine Kategorie und markieren Sie die zuzuordnenden Chats.|Noch keine Telegram-Sendungen.",
 ru: "Чаты|Канал|Личный чат|Сеанс Telegram будет закрыт, а аккаунт архивирован в Logivya.|Отправленные сообщения будут удалены у всех получателей Telegram. Это действие нельзя отменить.|По условиям тарифа в конец сообщения добавляется подпись Logivya.|Сообщение с подписью превышает лимит Telegram. Сократите текст.|Поиск чата или канала|Выберите категорию и отметьте чаты для назначения.|Отправок Telegram пока нет.",
 ro: "Conversații|Canal|Conversație privată|Sesiunea Telegram se va închide, iar contul va fi arhivat în Logivya.|Mesajele trimise vor fi șterse pentru toți destinatarii Telegram. Acțiunea este ireversibilă.|Planul adaugă o mențiune Logivya la sfârșitul mesajului.|Mesajul și mențiunea depășesc limita Telegram. Scurtați textul.|Caută conversații sau canale|Alegeți o categorie, apoi bifați conversațiile de atribuit.|Încă nu există trimiteri Telegram.",
 az: "Söhbətlər|Kanal|Şəxsi söhbət|Telegram sessiyası bağlanacaq və hesab Logivya’da arxivləşdiriləcək.|Göndərilmiş mesajlar bütün Telegram alıcılarından silinəcək. Bunu geri qaytarmaq olmaz.|Paketinizə uyğun olaraq mesajın sonuna Logivya tanıtım qeydi əlavə olunur.|Mesaj və tanıtım qeydi Telegram limitini aşır. Mətni qısaldın.|Söhbət və ya kanal axtar|Kateqoriya seçin, sonra təyin ediləcək söhbətləri işarələyin.|Hələ Telegram göndərişi yoxdur.",
 tk: "Söhbetler|Kanal|Şahsy söhbet|Telegram sessiýasy ýapylar we hasap Logivya’da arhiwlener.|Iberilen habarlar ähli Telegram alyjylaryndan pozular. Muny yzyna gaýtaryp bolmaz.|Bukjaňyza görä habaryň soňuna Logivya tanyşdyryş ýazgysy goşulýar.|Habar we tanyşdyryş ýazgysy Telegram çäginden geçýär. Teksti gysgaldyň.|Söhbet ýa-da kanal gözle|Kategoriýa saýlaň, soň degişli söhbetleri belläň.|Entek Telegram iberişi ýok.",
 bg: "Чатове|Канал|Личен чат|Сесията в Telegram ще бъде затворена, а акаунтът архивиран в Logivya.|Изпратените съобщения ще бъдат изтрити за всички получатели в Telegram. Това е необратимо.|Планът ви добавя подпис на Logivya в края на съобщението.|Съобщението и подписът надвишават лимита на Telegram. Съкратете текста.|Търси чат или канал|Изберете категория и маркирайте чатовете за присвояване.|Все още няма изпращания в Telegram.",
 el: "Συνομιλίες|Κανάλι|Ιδιωτική συνομιλία|Η συνεδρία Telegram θα κλείσει και ο λογαριασμός θα αρχειοθετηθεί στο Logivya.|Τα απεσταλμένα μηνύματα θα διαγραφούν για όλους τους παραλήπτες στο Telegram. Αυτό δεν αναιρείται.|Το πακέτο σας προσθέτει αναφορά στο Logivya στο τέλος του μηνύματος.|Το μήνυμα και η αναφορά υπερβαίνουν το όριο του Telegram. Συντομεύστε το κείμενο.|Αναζήτηση συνομιλίας ή καναλιού|Επιλέξτε κατηγορία και σημειώστε τις συνομιλίες προς ανάθεση.|Δεν υπάρχουν αποστολές Telegram ακόμη.",
 sr: "Razgovori|Kanal|Privatni razgovor|Telegram sesija će se zatvoriti, a nalog arhivirati u Logivya.|Poslate poruke biće obrisane kod svih Telegram primalaca. Ovo se ne može opozvati.|Vaš paket dodaje Logivya potpis na kraju poruke.|Poruka i potpis prelaze Telegram ograničenje. Skratite tekst.|Pretraži razgovore ili kanale|Izaberite kategoriju, pa označite razgovore za dodelu.|Još nema Telegram slanja.",
};
const keys = ['chats','channel','privateChat','archiveDescription','deleteDescription','brandingNotice','messageTooLong','searchAudience','categoryHelp','noHistory'] as const;
export function telegramManagementExtra(locale: string) { const values=(rows[locale] ?? rows.en!).split('|'); return Object.fromEntries(keys.map((key,i)=>[key,values[i]])) as Record<typeof keys[number],string>; }
export function validateTelegramManagementExtra() { return Object.values(rows).every(row=>row.split('|').length===keys.length); }
