import { additionalTelegramConnection } from './telegram-connection-locales';
import common from './telegram-connection-common.json';
const en = {
  add: "Connect a Telegram account", connect: "Connect", restart: "Resume connection", refresh: "Refresh status", sync: "Sync chats",
  empty: "Connect your Telegram account to manage your chats here.",
  help: "Choose your country and enter the phone number registered with Telegram. Continue with the verification requested by Telegram.",
  phone: "Phone number", country: "Country code", search: "Search country or calling code", code: "Telegram verification code",
  password: "Two-step verification password", email: "Verification email", emailCode: "Email verification code", next: "Continue",
  phoneHelp: "Use the number of your existing Telegram account.",
  codeHelp: "Enter the code sent by Telegram. Check your Telegram app and, if offered by Telegram, your SMS messages.",
  passwordHelp: "Enter the two-step verification password you set in Telegram.",
  emailHelp: "Telegram needs an email address to verify this sign-in.", emailCodeHelp: "Enter the code Telegram sent to your email address.",
  otherDevice: "Approve the new sign-in request in your Telegram app. This page will update automatically.",
  starting: "Starting connection…", waiting: "Waiting for Telegram…", connected: "Connected", closed: "Connection required", failed: "Connection needs attention",
  accepted: "Submitted to Telegram. The next verification step will appear here.", done: "Your Telegram account is connected. You can now sync your chats.",
  syncDone: "Chats synced. Open the Chats tab to view them.", invalidPhone: "Enter a valid phone number for the selected country.",
  invalidAuth: "The code or password could not be verified. Check it and try again.",
  expired: "This code has expired. Use the latest code from Telegram.",
  limited: "Please wait before trying again.", restricted: "Telegram has restricted this number. Check the account in Telegram.",
  changed: "The verification step has changed. Continue with the current step.", unavailable: "Telegram is temporarily unavailable. Refresh the status and try again.",
  failure: "The operation could not be completed. Please try again.", signedOut: "Please sign in again to continue.",
  hiddenError: "Telegram could not complete the last step. Check your details or resume the connection.",
  seconds: "seconds", hint: "Password hint", noCountries: "No country found.",
};
type Copy = typeof en;
const tr: Copy = {
  add: "Telegram hesabı bağla", connect: "Bağlan", restart: "Bağlantıya devam et", refresh: "Durumu yenile", sync: "Sohbetleri eşitle",
  empty: "Sohbetlerinizi burada yönetmek için Telegram hesabınızı bağlayın.",
  help: "Ülkenizi seçip Telegram'a kayıtlı telefon numaranızı girin. Telegram'ın istediği doğrulama adımlarıyla devam edin.",
  phone: "Telefon numarası", country: "Ülke kodu", search: "Ülke veya telefon kodu ara", code: "Telegram doğrulama kodu",
  password: "İki aşamalı doğrulama parolası", email: "Doğrulama e-postası", emailCode: "E-posta doğrulama kodu", next: "Devam et",
  phoneHelp: "Mevcut Telegram hesabınızın telefon numarasını kullanın.",
  codeHelp: "Telegram'ın gönderdiği kodu girin. Telegram uygulamanızı ve Telegram sunuyorsa SMS mesajlarınızı kontrol edin.",
  passwordHelp: "Telegram'da belirlediğiniz iki aşamalı doğrulama parolasını girin.",
  emailHelp: "Telegram bu giriş için bir doğrulama e-postası istiyor.", emailCodeHelp: "Telegram'ın e-posta adresinize gönderdiği kodu girin.",
  otherDevice: "Telegram uygulamanızdaki yeni oturum açma isteğini onaylayın. Bu ekran otomatik güncellenecek.",
  starting: "Bağlantı başlatılıyor…", waiting: "Telegram yanıtı bekleniyor…", connected: "Bağlı", closed: "Bağlantı gerekli", failed: "Bağlantının kontrol edilmesi gerekiyor",
  accepted: "Bilgiler Telegram'a iletildi. Sonraki doğrulama adımı burada görünecek.", done: "Telegram hesabınız bağlandı. Artık sohbetlerinizi eşitleyebilirsiniz.",
  syncDone: "Sohbetler eşitlendi. Sohbetler sekmesinden görüntüleyebilirsiniz.", invalidPhone: "Seçtiğiniz ülkeye uygun, geçerli bir telefon numarası girin.",
  invalidAuth: "Kod veya parola doğrulanamadı. Kontrol edip tekrar deneyin.", expired: "Kodun süresi doldu. Telegram'daki güncel kodu kullanın.",
  limited: "Yeniden denemeden önce bekleyin.", restricted: "Telegram bu numarayı kısıtladı. Hesabınızı Telegram uygulamasından kontrol edin.",
  changed: "Doğrulama adımı değişti. Güncel adımla devam edin.", unavailable: "Telegram bağlantısına şu anda ulaşılamıyor. Durumu yenileyip tekrar deneyin.",
  failure: "İşlem tamamlanamadı. Lütfen tekrar deneyin.", signedOut: "Devam etmek için yeniden giriş yapın.",
  hiddenError: "Telegram son adımı tamamlayamadı. Bilgilerinizi kontrol edin veya bağlantıya devam edin.",
  seconds: "saniye", hint: "Parola ipucu", noCountries: "Ülke bulunamadı.",
};
const uz: Copy = {
  add: "Telegram hisobini ulash", connect: "Ulanish", restart: "Ulanishni davom ettirish", refresh: "Holatni yangilash", sync: "Chatlarni sinxronlash",
  empty: "Chatlarni shu yerda boshqarish uchun Telegram hisobingizni ulang.",
  help: "Mamlakatingizni tanlang va Telegram hisobingiz telefon raqamini kiriting. Telegram so‘ragan tasdiqlash bosqichlarini bajaring.",
  phone: "Telefon raqami", country: "Mamlakat kodi", search: "Mamlakat yoki telefon kodini qidirish", code: "Telegram tasdiqlash kodi",
  password: "Ikki bosqichli tasdiqlash paroli", email: "Tasdiqlash uchun elektron pochta", emailCode: "Elektron pochta tasdiqlash kodi", next: "Davom etish",
  phoneHelp: "Mavjud Telegram hisobingiz telefon raqamidan foydalaning.",
  codeHelp: "Telegram yuborgan kodni kiriting. Telegram ilovasini va Telegram taklif qilsa, SMS xabarlarini tekshiring.",
  passwordHelp: "Telegram’da o‘rnatgan ikki bosqichli tasdiqlash parolini kiriting.",
  emailHelp: "Telegram bu kirishni tasdiqlash uchun elektron pochta manzilini so‘ramoqda.", emailCodeHelp: "Telegram elektron pochtangizga yuborgan kodni kiriting.",
  otherDevice: "Telegram ilovasida yangi kirish so‘rovini tasdiqlang. Bu sahifa avtomatik yangilanadi.",
  starting: "Ulanish boshlanmoqda…", waiting: "Telegram javobi kutilmoqda…", connected: "Ulangan", closed: "Ulanish kerak", failed: "Ulanishni tekshirish kerak",
  accepted: "Ma’lumotlar Telegram’ga yuborildi. Keyingi tasdiqlash bosqichi shu yerda ko‘rinadi.", done: "Telegram hisobingiz ulandi. Endi chatlarni sinxronlashingiz mumkin.",
  syncDone: "Chatlar sinxronlandi. Ularni Chatlar bo‘limida ko‘rishingiz mumkin.", invalidPhone: "Tanlangan mamlakat uchun to‘g‘ri telefon raqamini kiriting.",
  invalidAuth: "Kod yoki parol tasdiqlanmadi. Tekshirib, qayta urinib ko‘ring.", expired: "Kodning muddati tugadi. Telegram’dagi yangi koddan foydalaning.",
  limited: "Qayta urinishdan oldin kuting.", restricted: "Telegram bu raqamni cheklagan. Hisobni Telegram ilovasida tekshiring.",
  changed: "Tasdiqlash bosqichi o‘zgardi. Joriy bosqichni davom ettiring.", unavailable: "Hozir Telegram’ga ulanib bo‘lmayapti. Holatni yangilab, qayta urinib ko‘ring.",
  failure: "Amal bajarilmadi. Qayta urinib ko‘ring.", signedOut: "Davom etish uchun qayta kiring.",
  hiddenError: "Telegram oxirgi bosqichni bajara olmadi. Ma’lumotlarni tekshiring yoki ulanishni davom ettiring.",
  seconds: "soniya", hint: "Parol eslatmasi", noCountries: "Mamlakat topilmadi.",
};
const ar: Copy = {
  add: "ربط حساب تيليجرام", connect: "اتصال", restart: "متابعة الاتصال", refresh: "تحديث الحالة", sync: "مزامنة المحادثات",
  empty: "اربط حساب تيليجرام لإدارة محادثاتك هنا.", help: "اختر بلدك وأدخل رقم الهاتف المسجل في تيليجرام، ثم أكمل خطوات التحقق المطلوبة.",
  phone: "رقم الهاتف", country: "رمز البلد", search: "ابحث عن البلد أو رمز الاتصال", code: "رمز التحقق من تيليجرام",
  password: "كلمة مرور التحقق بخطوتين", email: "البريد الإلكتروني للتحقق", emailCode: "رمز التحقق عبر البريد", next: "متابعة",
  phoneHelp: "استخدم رقم هاتف حسابك الحالي في تيليجرام.", codeHelp: "أدخل الرمز الذي أرسله تيليجرام. تحقق من التطبيق أو الرسائل النصية إذا أتاحها تيليجرام.",
  passwordHelp: "أدخل كلمة مرور التحقق بخطوتين التي حددتها في تيليجرام.", emailHelp: "يطلب تيليجرام بريداً إلكترونياً للتحقق من تسجيل الدخول.", emailCodeHelp: "أدخل الرمز الذي أرسله تيليجرام إلى بريدك الإلكتروني.",
  otherDevice: "وافق على طلب تسجيل الدخول في تطبيق تيليجرام. ستتحدث هذه الصفحة تلقائياً.",
  starting: "جارٍ بدء الاتصال…", waiting: "في انتظار تيليجرام…", connected: "متصل", closed: "الاتصال مطلوب", failed: "يجب التحقق من الاتصال",
  accepted: "تم إرسال المعلومات إلى تيليجرام. ستظهر خطوة التحقق التالية هنا.", done: "تم ربط حساب تيليجرام. يمكنك الآن مزامنة المحادثات.",
  syncDone: "تمت مزامنة المحادثات. افتح تبويب المحادثات لعرضها.", invalidPhone: "أدخل رقم هاتف صالحاً للبلد المحدد.",
  invalidAuth: "تعذر التحقق من الرمز أو كلمة المرور. تحقق وحاول مجدداً.", expired: "انتهت صلاحية الرمز. استخدم أحدث رمز من تيليجرام.",
  limited: "يرجى الانتظار قبل المحاولة مجدداً.", restricted: "قيّد تيليجرام هذا الرقم. تحقق من الحساب في تطبيق تيليجرام.",
  changed: "تغيرت خطوة التحقق. تابع الخطوة الحالية.", unavailable: "تعذر الوصول إلى تيليجرام حالياً. حدّث الحالة وحاول مجدداً.",
  failure: "تعذر إكمال العملية. حاول مجدداً.", signedOut: "يرجى تسجيل الدخول مجدداً للمتابعة.",
  hiddenError: "لم يتمكن تيليجرام من إكمال الخطوة الأخيرة. تحقق من المعلومات أو تابع الاتصال.",
  seconds: "ثانية", hint: "تلميح كلمة المرور", noCountries: "لم يتم العثور على بلد.",
};
export function telegramConnectionCopy(locale: string): Copy {
 const code=locale.split('-')[0]!;
 const base=({tr,en,uz,ar} as Record<string,Copy>)[code];if(base)return base;
 const extra=additionalTelegramConnection(code);if(!extra)return en;
 return { ...extra, ...(common as Record<string,Record<string,string>>)[code], empty:extra.help, phoneHelp:extra.help, failed:extra.unavailable, hiddenError:extra.invalidAuth } as Copy;
}
