import assert from "node:assert/strict";
import { extractFreightCandidates } from "../src/server/freight/message-extraction";
import { splitSourceRoutes } from "../src/server/freight/source-routes";
import { findLogisticsLocationOccurrences } from "../src/server/freight/location-normalization";

const at = new Date("2026-09-05T06:00:00Z");
const candidates = extractFreightCandidates("Adana Yüreğir→Adana Seyhan Kapalı/Tenteli Kamyonet 200kg Sakarya Hendek→Sakarya Adapazarı Frigo 22 ton", at);
assert.equal(candidates.length, 2);
assert.equal(candidates[0]?.origin?.canonical, "Adana Yüreğir");
assert.equal(candidates[0]?.destination?.canonical, "Adana Seyhan");
assert.equal(candidates[0]?.weight, 0.2);
assert.equal(candidates[1]?.weight, 22);
assert.equal(candidates[1]?.trailerType, "REFRIGERATED");
assert.doesNotMatch(candidates[0]?.sourceExcerpt ?? "", /Sakarya/);
assert.doesNotMatch(candidates[1]?.sourceExcerpt ?? "", /Adana/);
const mixed = extractFreightCandidates("!!Günlük taşıma görevi!! Tekirdağ Çorlu→Van 🚚 Kapalı/Açık TIR📦 Tekirdağ Hayrabolu→Denizli Sarayköy 🚚 Frigo 12ton 📦 Tekirdağ Çorlu→Bursa 🚚 Tenteli 15ton", at);
assert.equal(mixed.length, 3);
assert.equal(mixed[0]?.origin?.canonical, "Tekirdağ Çorlu");
assert.equal(mixed[0]?.destination?.canonical, "Van");
assert.equal(mixed[0]?.weight, null, "No weight may be borrowed from the next route");
assert.notEqual(mixed[0]?.trailerType, "VAN", "The city Van must not imply a panelvan");
assert.equal(mixed[1]?.weight, 12);
assert.equal(mixed[2]?.weight, 15);
assert.equal(mixed[2]?.origin?.canonical, "Tekirdağ Çorlu");
assert.equal(findLogisticsLocationOccurrences("panelvan taşıma").length, 0);
assert.equal(splitSourceRoutes("İstanbul, Ankara, Bursa, Adana 20 ton Tenteli")[0]?.origin, null);
assert.equal(extractFreightCandidates("Türkiye İstanbul 20 ton Tenteli", at).length, 0, "Country and its city alone are not a route");
const countries = extractFreightCandidates("Türkiye İstanbul → İran Tahran Frigo 20 ton", at);
assert.equal(countries[0]?.origin?.canonical, "İstanbul");
assert.equal(countries[0]?.destination?.canonical, "Tahran");
assert.equal(countries[0]?.weight, 20);
const incomplete = extractFreightCandidates("Adana → Sakarya Tenteli Mersin Ankara 22 ton", at);
assert.equal(incomplete[0]?.weight, null, "An unparsed route cannot supply another route's attributes");
const intra = extractFreightCandidates("Bursa Mudanya--Bursa Osmangazi Tenteli 2 ton", at);
assert.equal(intra.length, 1);
assert.equal(intra[0]?.origin?.canonical, "Bursa Mudanya");
assert.equal(intra[0]?.destination?.canonical, "Bursa Osmangazi");
console.log("Source route isolation, repeated cities, attributes and ambiguity checks passed.");
for (const city of ["Kocaeli Gölcük", "Kocaeli İzmit", "Kocaeli Dilovası"]) {
  const route = extractFreightCandidates(`${city} → İstanbul Tuzla Tenteli 75kg`, at)[0];
  assert.equal(route?.origin?.canonical, city);
  assert.equal(route?.destination?.canonical, "İstanbul Tuzla");
  assert.equal(route?.weight, 0.075);
}
assert.equal(extractFreightCandidates("Yükleme: Konya → Irak Frigo 25 ton", at)[0]?.cargoType, null, "Loading labels are not cargo descriptions");
assert.equal(extractFreightCandidates("Yük türü: Demir; Adana → Mersin Tenteli 20 ton", at)[0]?.cargoType, "Demir");
assert.equal(extractFreightCandidates(`Yük: ${"a".repeat(79)}🚚; Adana → Mersin Tenteli 20 ton`, at)[0]?.cargoType?.isWellFormed(), true, "A truncated emoji cannot produce invalid database text");
