ALTER TYPE "AccountStatus" ADD VALUE IF NOT EXISTS 'PENDING_PAIRING';
ALTER TYPE "AccountStatus" ADD VALUE IF NOT EXISTS 'PAIRING_CODE_READY';
ALTER TYPE "AccountStatus" ADD VALUE IF NOT EXISTS 'FAILED';
