ALTER TYPE "SubscriptionStatus" ADD VALUE IF NOT EXISTS 'SUSPENDED';
ALTER TYPE "PaymentStatus" ADD VALUE IF NOT EXISTS 'MANUALLY_CONFIRMED';
ALTER TYPE "PaymentStatus" ADD VALUE IF NOT EXISTS 'REJECTED';
ALTER TYPE "PaymentMethod" ADD VALUE IF NOT EXISTS 'MANUAL';
ALTER TYPE "PaymentMethod" ADD VALUE IF NOT EXISTS 'FREE_PROMO';
